### ISSUE TITLE
How to build a circle with outside border

### ISSUE THREAD

**Issue by walksin** [facebook/fresco#104]
I am using xml to make a circle image

     <style name="Avatar">
        <item name="placeholderImage">@drawable/avatar_default</item>
        <item name="roundAsCircle">true</item>
        <item name="actualImageScaleType">fitCenter</item>
        <item name="roundingBorderColor">@color/avatar_border</item>
        <item name="roundingBorderWidth">@dimen/dp_2.5</item>
    </style>

and the result is inside border, I want to use a color like #1E000000 border outside, pls help...

**Comment by plamenko** [comment]
The problem is that drawing a border outside of the view bounds would make it appear cropped. The grayed out parts would not be visible and you would only see what's depicted by a red color:

![outside](https://cloud.githubusercontent.com/assets/3705123/7025823/f3b14014-dd3d-11e4-8df9-b1fdf06c2a92.png)
