### ISSUE TITLE
Lib Size using ProGuard

### ISSUE THREAD

**Issue by HugoGresse** [facebook/fresco#1051]
The documentation say that 
> Fresco’s large download may seem intimidating, but it need not leave you with a large application. We strongly recommend use of the ProGuard tool.

I've just add Fresco dependencies to my application, generate my apk (with ProGuard) whitout any call to Fresco, apk size is now **2.6MB bigger**, passing from 1.4 to **4MB**.

Well, it's not very lite, cannot your proguard rules be optimized?

**Comment by balazsbalazs** [comment]
We're working on making the library size smaller and writing a post/doc about what to do to make your app smaller.
In general if you don't need any additional functionality it will be ~600k or less.

The reason why it's so big is because we're using a bunch of open source native libraries for additional functionality (eg. webp support back to Gingerbread, animated gif and animated webp, etc). The native libraries have .so files for all the architectures (x86, armv7, arm, etc) so if you're not building different apk's for different architectures all of them will be included in your apk.

We're planning to make the extra features optional and writing a doc about how to minimize the library size.

**Comment by HugoGresse** [comment]
thanks for the answer. It will we great to select which functionallity we want as we do with Google Play Services for example.
