### ISSUE TITLE
How can i get Bitmp before the picture display?

### ISSUE THREAD

**Issue by Mixiaomi** [facebook/fresco#1054]
How can i get Bitmp before the picture display? if I want show picture with full Screen width,Height according to the width of the display image isometric？thanks。

**Comment by ivanviragine** [comment]
This example: http://frescolib.org/docs/listening-download-events.html#usage shows you how to get the image dimensions, but since it doesn't have a reference to the drawee itself, you could achieve this only by making it final and referencing it inside the controller, but this wouldn't work in a recyclerview/adapter scheme, I guess.
