### ISSUE TITLE
Why I can‘t get Bitmap after display,what can i do ;

### ISSUE THREAD

**Issue by Mixiaomi** [facebook/fresco#1055]
Why I can‘t get Bitmap after display,what can i do ;

**Comment by massimocarli** [comment]
We manage the memory using a deterministic approach in order to optimize its usage. Anyway you can use a [BaseDataSubscriber](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/fbcore/src/main/java/com/facebook/datasource/BaseDataSubscriber.java) but in this case you have to manage the memory on your own.
