### ISSUE TITLE
ZoomableDraweeView zoomed image not moved with single finger

### ISSUE THREAD

**Issue by rafaelekol** [facebook/fresco#1182]
After zooming image in ZoomableDraweeView, I can't move image with single finger. I can move it with two fingers.

**Comment by plamenko** [comment]
Is your ZoomableDraweeView in some container that intercepts touch events like a PagerView?

**Comment by rafaelekol** [comment]
Yes ZoomableDraweeView is used inside page of PagerView.

**Comment by plamenko** [comment]
Yeah, it's hard to tell what exactly causes PagerView to consume those events without knowing how you are using it.

Are you saying that you first zoom-in the photo and then, while it's zoomed in, you are unable to pan with a single finger? If that's the case I'm not really sure what's going on because ZoomableDraweeView is doing [getParent().requestDisallowInterceptTouchEvent](https://github.com/facebook/fresco/blob/9caa0fe12aafba7383816e7f48abbf4a883e34f3/samples/zoomable/src/main/java/com/facebook/samples/zoomable/ZoomableDraweeView.java#L264).

You can put some breakpoints or logs there and see what events ZoomableDraweeView gets. We already have some verbose logging there.

**Comment by rafaelekol** [comment]
You were right.
In my code touch consumer was this part of code inside onTouchListener for ZoomableDraweeView. Removing it fixed problem.

```
@Override
            public boolean onDown(MotionEvent e) {
                return true;
            }
```
