### ISSUE TITLE
How to resolve package conflicts

### ISSUE THREAD

**Issue by ZheLE** [facebook/fresco#1268]
Hello,
My android project using network load fresco picture, and now I need to put a Third-party communications framework (Ali Wukong) into my project, to achieve a chat, and then compile the project error
Error Log
Error: Execution failed for task ': app: transformNative_libsWithMergeJniLibsForDebug'.
> Com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi/ libmemchunk.so
   File1: ..................../app/build/intermediates/exploded-aar/wukongim_1.3.4.9-UT-SNAPSHOT/jni
   File2: ..................../app/build/intermediates/exploded-aar/com.facebook.fresco/imagepipeline/0.10.0/jni

I think it should be the internal communication framework has introduced a fresco, what is the solution ......
Thank you!

**Comment by ZheLE** [comment]
I quote the form of third-party packages by aar
build.gradle file
repositories {
    mavenCentral()
    flatDir {
        dirs 'aars'
    }
}

//Third-party communications framework aar
compile(name: 'wukongim_1.3.4.9-UT-SNAPSHOT', ext: 'aar')
compile(name: 'doraemon-multimedia-1.9.5.0-SNAPSHOT', ext: 'aar')
// fresco jar
compile 'com.facebook.fresco:fresco:0.10.0'

**Comment by michalgr** [comment]
Are you sure that the communication framework includes Fresco ? Gradle is not supposed to put dependencies of library in the same aar. Normally those dependencies are specified in pom.xml files and gradle knows to download them together with the library if the library is needed. This way gradle can handle complex dependencies graphs without conflicts.

It is possible that the communication framework your app depends on uses the same name for one of its native libraries as Fresco does. This way both aars would include 'libmemchunk.so' but each of those would be a different library, in which case you'll have to rename libmemchunk.so to something else either by forking Fresco or changing source code of the communication framework.

Is the source of the communication framework available anywhere so that I can have a look ?

**Comment by ZheLE** [comment]
The communications framework source code is not disclosed.
You mean communications framework and a fresco also references the same name as the library 'libmemchunk.so’，but each of those would be a different library,They are just the same name。

**Comment by michalgr** [comment]
I downloaded their sdk and checked that libbitmaps.so and libmemchunk.so are included in one of their aars. I cannot find Fresco classes using them in those aars, so I think those libraries were included there "by mistake". You should be able to remove them from wukongim_1.3.4.9-UT-SNAPSHOT.aar. Also it might be a good idea to ping maintainers of the communication framework and ask them to fix this.
