### ISSUE TITLE
blink

### ISSUE THREAD

**Issue by Fisherman91** [facebook/fresco#1277]
When I load the same picture, how to make SimpleDraweeView not blink? Because now even load the same image will be displayed first placeholder Image, and then display the images after loading. .

**Comment by aagnes** [comment]
By design, placeholder is used for display before getting actual image. Is that what you mean by blink?

**Comment by plamenko** [comment]
That's strange because if the image is visible, it should be in the bitmap cache. If you set the same image again to a view, it should find the image in the bitmap cache immediately and there should be no flicker. 

There are a couple of possibilities:
* the uri and/or request parameters are actually not exactly the same
* the image was not found in cache (shouldn't happen)
* there is a bug in the drawee logic
* something else

Please follow our troubleshooting section and provide the logcat output that will tell us more.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
