### ISSUE TITLE
WebP with alpha on API 17

### ISSUE THREAD

**Issue by paulzin** [facebook/fresco#1285]
I'm using `compile 'com.facebook.fresco:webpsupport:0.10.0'` to support transparent webp images on devices < 18 API (API 18 is when native support was added to framework).

But on some devices on **API 17** (for example Huawei Ascend G700) I'm facing this weird bug: [screenshot](http://i.imgur.com/las5poh.png) (for the reference, it should look like [this](http://i.imgur.com/rFqZiR0.png)). These webp images are from [official google samples](https://developers.google.com/speed/webp/gallery2#side-by-side_comparison) (WebP-lossy with alpha).

Is there some workaround about this?

**Comment by aagnes** [comment]
@massimocarli

**Comment by massimocarli** [comment]
Hi @paulzin,
it looks like the transparent Webp are recognized as simple or enhanced Webp and so transparent information are lost. We should check what the format recognized by the ImageFormatChecker and WebpTranscodeProducer classes. If you can reproduce the problem can you please put some breakpoint into the doTranscode() method in WebpTranscodeProducer and see what's the recognized type for that images? Basically [here](https://github.com/facebook/fresco/blob/b3c1a9643d901457c5db1af33320926622270f77/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/WebpTranscodeProducer.java#L182)
Thanks

**Comment by paulzin** [comment]
Hi, @massimocarli. I looked into this bug and found some interesting results:
- **setWebpSupportEnabled(false)**: doTranscode() is never called, shouldTranscode() is called and detects WEBP_EXTENDED_WITH_ALPHA, in onNewResultImpl() mShouldTranscodeWhenFinished is NO, so transcodeLastResult() is never called;
- **setWebpSupportEnabled(true)**: onNewResultImpl() is never called, as well as other methods described above.

**Comment by massimocarli** [comment]
Hi @paulzin 
The setWebpSupportEnabled() is a configuration method that you should call to decide if using the webp transcoding to jpg or png or using our experimental webp decoder. I suggested to see both cases in order to see if this was a transconding or decoding problem. 
Thanks

**Comment by paulzin** [comment]
@massimocarli I reckon the problem is with decoding, as I'm getting the same bug with setWebpSupportEnabled(false).

**Comment by zjupure** [comment]
@massimocarli I have met this problem too. On some API <=17 devices, webp with alpha cannot be decoded normally. After some investigation, I found fresco use the wrong colorspace to decode webp in [webp_bitmapfactory.cpp](https://github.com/facebook/fresco/blob/master/static-webp/src/main/jni/static-webp/webp_bitmapfactory.cpp#L148) . The colorspace should be `MODE.rgbA` not `MODE.RGBA`, because in Android system, Bitmap pixel array are pre-multiplied by default. You can see in [webp.cpp](https://github.com/facebook/fresco/blob/master/static-webp/src/main/jni/static-webp/webp.cpp#L650) which account for decoding animated webp images, `MODE.rgbA` is using there, so webp frames with alpha can be displayed correctly.
