### ISSUE TITLE
can't open file in assets folder

### ISSUE THREAD

**Issue by hirogen317** [facebook/fresco#13]
I tried SimpleDraweeView.setImageURI and set a file:///android_asset resource.
> xx.setImageURI(Uri.parse("file:///android_asset/....jpg"));
But it shows an error:
> can't open '/android_asset/xxx.jpg' 
And if I use:
> xx.setImageDrawable(new BitmapDrawable(getAssets().open("xxx.jpg")));
This is correct.
I am new to android. Do I make some mistakes? If there are some problems, please let me know. :-)

**Comment by IanChilds** [comment]
Can you try asset://...jpg? See http://frescolib.org/docs/supported-uris.html

**Comment by hirogen317** [comment]
Thank you, IanChilds. Resolved.
I am sorry that I failed to reach the document.
I use:
> Uri.parse("asset:///...")
and solved this problem.

**Comment by IanChilds** [comment]
No problem. Hope you find Fresco useful!

**Comment by quynhbk** [comment]
I can't load from:
newUrl = "assets://images/common/place_detail/default_place.png";
heap me1

**Comment by anotherdev** [comment]
@quynhbk you are using UIL scheme. Fresco one doesn't have **s** (use `asset://`);

Fresco should support `file:///android_asset/` instead of creating new scheme and don't documented clearly that `asset://` scheme is vendor specific.

Picasso: https://github.com/square/picasso/issues/332
Glide: http://stackoverflow.com/questions/29982341/using-glide-for-android-how-do-i-load-images-from-asset-and-resources

**Comment by Dima564** [comment]
+1 to file:///android_asset/

**Comment by tarifchakder** [comment]
val inputStream : InputStream = context.assets.open("image/myimg.png")
val bitmap = BitmapFactory.decodeStream(inputStream)
img.setImageBitmap(bitmap)
