### ISSUE TITLE
High Memory Usage with 0.11.0

### ISSUE THREAD

**Issue by embydextrous** [facebook/fresco#1311]
I have been using fresco in my project and updated from version 0.10.0 to 0.11.0.
In case of adapters displaying image in viewholders there is a large memory usage in version 0.11.0 and the memory is not getting freed leading to slow scroll.

I am new to memory leaks and don't know how to use MAT so I reverted back to version 0.10.0.

Also, image loading is relatively slow. Is there some kind of imagepipeline configuration you can help with?

**Comment by oprisnik** [comment]
You noticed higher memory usage only with 0.11.0? How much of a difference is there compared to 0.10.0, how are you using Fresco and what kind of images.

For slow loading images: We need more information which images you're using (size, type etc.).

**Comment by embydextrous** [comment]
I figured out. My partner changed the way drawee works. He set up anonymous click listeners not freeing drawee views.

Well, I need a configuration to load simple .jpg images in a recycler view where each item has two drawee views. One image is very small while other is large. I am using ResizeOptions but still it is slow. 
I am also using ImagePipeline configuration from fresco samples - 'comparison'. Can you suggest something else.

**Comment by oprisnik** [comment]
Good to hear that you solved the issue.

You should consider only serving images that roughly match the size of your views so that you don't have to fetch huge images that are never used. This decreases the network traffic for your user and speeds up everything.
If you have to use resizing, take a look at the documentation here: http://frescolib.org/docs/resizing-rotating.html

If by 2 images you mean a low-res and a high-res image on top of each other: We support this out-of-the-box. The DraweeControllerBuilder has `setLowResImageRequest` and `setImageRequest`.
