### ISSUE TITLE
AnimatedDrawable usage

### ISSUE THREAD

**Issue by DukeLee1989** [facebook/fresco#1313]
can  I inherit AnimatedDrawable achieve other functions?

**Comment by oprisnik** [comment]
What exactly do you want to do? 
You can extend AnimatedDrawable and use it manually. If you want to use your own AnimatedDrawable extension with GIFs automatically with Fresco, I don't think that we provide an easy way to do this.
You would have to modify `AnimatedDrawableFactoryImpl` to return your drawable that extends AnimatedDrawable or create a new `AnimatedDrawableFactoryImpl` for your case.

**Comment by DukeLee1989** [comment]
If a GIF picture is large, more than 4096*4096, I would like to use BitmapRegionDecoder class  to  break up.What do I do?

**Comment by DukeLee1989** [comment]
Of course, GIT to download the use of fresco.

**Comment by DukeLee1989** [comment]
@oprisnik help me.

**Comment by oprisnik** [comment]
I think there is no easy way to do this without changing Fresco. I would suggest that you use smaller GIFs from the beginning (maybe let the server resize them for you) since such large GIFs will take up a lot of network traffic and it will also take quite some time to decode them (see #1231 for example).
We currently don't support downsampling for the image and resizing.

**Comment by oprisnik** [comment]
It's possible to create a custom decoder and DrawableFactory that does what you want, see https://github.com/facebook/fresco/tree/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat for some examples.
