### ISSUE TITLE
how many times to retry before failureimage is shown? 

### ISSUE THREAD

**Issue by lovearthhome** [facebook/fresco#1341]
using fresco, i set retryiamge and failure iamge,

as i observed, in absence of network (image can not be downloaed),  i need to press retry image 2~5 times before failure image shown. 

why is that? where to configure the retry count. 

or

after i press retryImage once, the image request is fired, before the response arrive, i can press retryImge again and again? once reponse arrive saying that network is non-available, failure image shown ?

-----------------update-----

i am sure that:

i press the retryImage once, one iamgeRequest is fired!
press twice fire two imageRequest

**Comment by massimocarli** [comment]
All the retry logic in encapsulated into the [RetryManager](https://github.com/facebook/fresco/blob/df2854a76786f58e044a71617309cc3c0a0c358c/drawee/src/main/java/com/facebook/drawee/components/RetryManager.java) class. In order to enable this you have to invoke the `setTapToRetryEnabled()` method in the `DraweeControllerBuilder`. The default number of retry is 4 but you can obviously change it.
Thanks

**Comment by massimocarli** [comment]
Hi @lovearthhome,
you're right. At the moment the only way is to create a class which extends RetryManager and implements the new logic. We'll add the API asap.
Thanks

**Comment by cuongmanhvo162** [comment]
Hello @massimocarli , do we have an API to custom the retry number?

Thank you.
