### ISSUE TITLE
Building depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by narychen** [facebook/fresco#1358]
I tried to build fresco into my project so that I could change some of the code.
Put 

```
include ':fbcore'
include ':drawee'
include ':imagepipeline'
include ':imagepipeline-base'
```

in settings.gradle
and

```
    compile project(':fbcore')
    compile project(':imagepipeline-base')
    compile project(':imagepipeline')
    compile project(':drawee')
```

in build.gradle instead of compile 'com.facebook.fresco:fresco:0.10.0'
I got 
Warning:Module 'com.facebook.fresco:imagepipeline-base:0.10.0' depends on one or more Android Libraries but is a jar
and couldn't run the app due to prepareDependecies failure

I built the whole package git clone from github and it has no problem. 
I don't know  why gradle keep warn me imagepipeline-base and imagepipeline is jar but not with drawee.

**Comment by eldk** [comment]
Hello,

I have it running on one app project with Fresco 0.11.0. 

1- clone the Fresco repository on a local folder, out of Android Studio project folder
2 - modify project settings gradle :

`include ':app'`
`include ':fbcore'`
`project(':fbcore').projectDir = new File('/way_out_of_project/to/git/fresco/fbcore')`
`include ':drawee'`
`project(':drawee').projectDir = new File('/way_out_of_project/to/git//drawee')`
`include ':drawee-backends:drawee-pipeline'`
`project(':drawee-backends:drawee-pipeline').projectDir = new File('/way_out_of_project/to/git/fresco/drawee-backends/drawee-pipeline')`
`include ':imagepipeline'`
`project(':imagepipeline').projectDir = new File('/way_out_of_project/to/git/fresco/imagepipeline')`
`include ':imagepipeline-base'`
`project(':imagepipeline-base').projectDir = new File('/way_out_of_project/to/git/fresco/imagepipeline-base')`

because gradle complain of some missing dependencies when build : 

`include ':imagepipeline-test'
project(':imagepipeline-test').projectDir = new File('/way_out_of_project/to/git/fresco/imagepipeline-test')`
`include ':imagepipeline-base-test'`
`project(':imagepipeline-base-test').projectDir = new File('/way_out_of_project/to/git/fresco/imagepipeline-base-test')`

optional : 

`include ':imagepipeline-backends:imagepipeline-okhttp3'`
`project(':imagepipeline-backends:imagepipeline-okhttp3').projectDir = new File(/way_out_of_project/to/git/fresco/imagepipeline-backends/imagepipeline-okhttp3')`
`include ':static-webp'`
`project(':static-webp').projectDir = new File('/way_out_of_project/to/git/fresco/static-webp')`

3 - I have added in app module build.gradle : 

`compile project(':fbcore')`
   ` compile project(':drawee')`
   ` compile project(':drawee-backends:drawee-pipeline')`
    `compile project(':imagepipeline')`
    `compile project(':imagepipeline-base')`

optional : 

    `compile project(':imagepipeline-backends:imagepipeline-okhttp3')`
    `compile project(':static-webp')`

4 - I have replaced my project build.gradle with the one used for Fresco project (as it is convenient to me) 

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${ANDROID_GRADLE_PLUGIN_VERSION}"
        classpath "de.undercouch:gradle-download-task:${GRADLE_DOWNLOAD_TASK_VERSION}"
        classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:${GRADLE_BINTRAY_PLUGIN_VERSION}"
        classpath "com.github.dcendents:android-maven-gradle-plugin:${ANDROID_MAVEN_GRADLE_PLUGIN_VERSION}"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

project.ext {
    buildToolsVersion = "${BUILD_TOOLS_VERSION}"
    compileSdkVersion = COMPILE_SDK_VERSION.toInteger()
    minSdkVersion = MIN_SDK_VERSION;
    targetSdkVersion = TARGET_SDK_VERSION;
    preDexLibs = !project.hasProperty('disablePreDex');
}

subprojects {

    repositories {
        mavenLocal()
        jcenter()
        mavenCentral()
    }

    task allclean {
    }

    afterEvaluate { project ->
        allclean.dependsOn(project.tasks.matching { it.name == 'clean' })

        if (project.tasks.matching { it.name == 'assembleRelease' }) {
            def jarList = new ArrayList()
            task setJarList(dependsOn: assembleRelease) << {
                configurations.compile.each {
                    jarList.add(it)
                }
            }

            task copyDeps(dependsOn: setJarList, type: Copy) {
                from jarList
                into 'build/external'
            }
        }
    }

    project.plugins.whenPluginAdded { plugin ->
        if ("com.android.build.gradle.AppPlugin".equals(plugin.class.name)) {
            project.android.dexOptions.preDexLibraries = rootProject.ext.preDexLibs
        } else if ("com.android.build.gradle.LibraryPlugin".equals(plugin.class.name)) {
            project.android.dexOptions.preDexLibraries = rootProject.ext.preDexLibs
        }
    }
}`

4.a - and use Fresco project gradle.properties file as my project properties - copyed in Android Studio project root folder
4.b - add/copyed release-bintray.gradle and release-sonatype.gradle from  to Android Studio project root folder

5 - in gradle Global properties file : 
`ndk.path=/way/to/sdk/ndk-bundle/r10e`
`org.gradle.daemon=true`
`org.gradle.parallel=true`
`org.gradle.configureondemand=true`

This way, I'm able to build without any error and use one forked repository from Fresco (https://github.com/eldk/fresco) with libs modification, and another one for my app project.

>I don't know why gradle keep warn me imagepipeline-base and imagepipeline is jar but not with drawee. 

I seems like drawee has a complete Android project structure thus other module are not. (Warnings from Crashlytics debug).

But not sure .

Hope that it helps.

**Comment by narychen** [comment]
@eldk I really thank you for this long reply. It may help, I will try it later. But still I wanna know why "Building depends on one or more Android Libraries but is a jar"  happened.

**Comment by erikandre** [comment]
Closing as a workaround was suggested. This is not a very common use case, so I believe that the workaround should be enough.
