### ISSUE TITLE
Stored in the cache

### ISSUE THREAD

**Issue by YoonKyoungTae** [facebook/fresco#1364]
Hi :D !
I want to know the duration of cache storage fresco.
Memorycache and Diskcache

How much for a long time a store?

**Comment by huangjunkun** [comment]
> com.facebook.cache.disk.DiskStorageCache#FUTURE_TIMESTAMP_THRESHOLD_MS
 > FUTURE_TIMESTAMP_THRESHOLD_MS = TimeUnit.HOURS.toMillis(2);


  /**
   * If any file timestamp is in the future (beyond now + FUTURE_TIMESTAMP_THRESHOLD_MS), we will
   * set its effective timestamp to 0 (the beginning of unix time), thus sending it to the head of
   * the queue for eviction (entries with the lowest timestamps are evicted first). This is a
   * safety check in case we get files that are written with a future timestamp.
   * We are adding a small delta (this constant) to account for network time changes, timezone
   * changes, etc.
   */

> com.facebook.imagepipeline.cache.CountingMemoryCache
> com.facebook.imagepipeline.cache.CountingLruMap

the store durtion of Both Memorycache and Diskcache depend on calling submit new image request.

Memorycache is evicted by LRU eviction strategy.
Diskcache is evicted by Comparing cache's timestamp to FUTURE_TIMESTAMP_THRESHOLD_MS  .

If you don't submit new image request, not update the cache , and the  cahe has always existed.

**Comment by kirwan** [comment]
Thanks @huangjunkun for your thorough answer. I'll close this issue as I think that answers it.

I'll add that both memory and disk cache employ LRU eviction. The future timestamp check in disk cache is additional to cover scenarios where the device time changes and cached items now appear to have been cached in the future. These could otherwise be retained indefinitely while more recent items are evicted.
