### ISSUE TITLE
About DraweeController Question

### ISSUE THREAD

**Issue by BruceeWang** [facebook/fresco#1365]
@InjectView(R.id.simpledraweeview)
 SimpleDraweeView simpleview;  

 @InjectView(R.id.simpleview)
SimpleDraweeView simpledraweeview;

Uri uri = Uri.parse("http://www..........");
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setProgressiveRenderingEnabled(true)
                .build();
        controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
                .setTapToRetryEnabled(true)
                .setOldController(simpledraweeview.getController())
                .setControllerListener(listener)
                .build();

        simpledraweeview.setController(controller);
        simpleview.setController(controller);

Why do I find the first simpledraweeview have no Loading image resource?The second simpleview load image exactly.Do not that view share the same controller?
（English is not very well,please excuse me）

**Comment by oprisnik** [comment]
You should use different controllers for different `DraweeViews`. 
Internally, each controller is bound to a `DraweeHierachy` (which holds the drawable that you see on screen and which is usually unique per DraweeView). When you attach a controller to a DraweeView, it updates the given hierarchy, so it will be set to the one of the second view for your example.

In theory, 2 views could share the same `DraweeHierarchy` (just set the same hierarchy for both, for example with `draweeView2.setHierarchy(draweeView1.getHierarchy())`). But then one of the views will not be updated when the state changes (e.g. when the network image is loaded) since the `Drawable.Callback` is set to only one of the two views. So the other view is not aware that it needs to update. It would be possible to write a custom `Drawable.Callback` that knows about all views that use the same `DraweeHierarchy` and invalidates all of them.
However, I would suggest that you use 2 separate controllers.
