### ISSUE TITLE
How can I save a image as a local file?

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#139]

**Comment by tyronen** [comment]
Use the image pipeline directly: http://frescolib.org/docs/using-image-pipeline.html.

Use the `fetchEncodedImage` method to get the image encoded. Then simply use a Java `FileOutputStream` to write it to a file.

**Comment by alex621** [comment]
So the image saved is not actually the original image right? It is, instead, a jpg file re-compressed from the Bitmap.

**Comment by tyronen** [comment]
No, it is the original image.

**Comment by leelei** [comment]
use '''fetchEncodedImage ''' , but it run on mian thread , Fresco already save Image as xxx.cnt, we donnot need save twice

**Comment by hubcin** [comment]
## I always get null `sourceBitmap` , here's my code: 
`private void saveImageToGallery() {
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(mUri)
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                .setPostprocessor(new Postprocessor() {
                    @Override
                    public CloseableReference<Bitmap> process(Bitmap sourceBitmap, PlatformBitmapFactory bitmapFactory) {
                        if (sourceBitmap != null) {
                            String path = MediaStore.Images.Media.insertImage(
                                    getContext().getContentResolver(),
                                    sourceBitmap, null, "download from Bainu"
                            );
                            if (path != null) {
                                Toast.makeImageToast(getContext(), R.drawable.icon_success, Toast.LENGTH_SHORT).show();
                            } else {
                                Toast.makeImageToast(getContext(), R.drawable.icon_failed, Toast.LENGTH_SHORT).show();
                            }
                        }
                        return null;
                    }

                    @Override
                    public String getName() {
                        return null;
                    }

                    @Override
                    public CacheKey getPostprocessorCacheKey() {
                        return null;
                    }
                }).build();
        imagePipeline.fetchEncodedImage(imageRequest, getContext());
    }`

**Comment by lambdapioneer** [comment]
Hi @hubcin, you do not want to use the post-processor for saving a Bitmap.

From `fetchEncodedImage` I guess that you want to fetch an encoded image. If you look at the return type, you see that you are getting a `DataSource<CloseableReference<PooledByteBuffer>>`. Subscribe to that in order to get the original image data. See http://frescolib.org/docs/using-image-pipeline.html

**Comment by hubcin** [comment]
Thank you @lambdapioneer , I think it's a little weird because this code works well in on of my service and I get my bitmap every time. But when I copy this code into one of my image displaying activity I found the bitmap always null. I have read the `using-image-pipline` section and `DataSources and DataSubscribers` section and used data subscribers to get the bitmap like:
```
dataSource.subscribe(new BaseBitmapDataSubscriber() {
    @Override
    public void onNewResultImpl(@Nullable Bitmap bitmap) {
      // You can use the bitmap here, but in limited ways.
      // No need to do any cleanup.
    }

    @Override
    public void onFailureImpl(DataSource dataSource) {
      // No cleanup required here.
    }
  },
  executor);
```
, but still the same null result. 
So I'm wondering if there would be any approach that I can get the bitmap directly without any surprise ? 
ps: In my application, the save image function will only be available when the image is loaded into `ImageView`, which means the image must be cached in disk or somewhere else, so I think the there's no reason for the bitmap to be null at all. 
Thanks.
