### ISSUE TITLE
Questions about implementing caching of output bitmaps for a PostProcessor

### ISSUE THREAD

**Issue by jmbusby** [facebook/fresco#1420]
I have a list of user thumbnails, some of which are blurred by a BlurPostProcessor. When the list gets dragged, I see the blurred images repeatedly fading in. I realized after some Googling that I need to add my PostProcessor output to the cache to prevent this.

I have read the documentation on adding caching to PostProcessors here:

http://frescolib.org/docs/modifying-image.html

I can't find any sample code for caching a PostProcessor output, so the documentation is all I have to go on.

Here's my PostProcessor and CacheKey implementation:

	public class BlurPostProcessor extends BasePostprocessor
	{
		private static class MyCacheKey implements CacheKey
		{
			private int mValue;
	
			public MyCacheKey(int value)
			{
				super();
				mValue = value;
			}
	
			@Override
			public boolean containsUri(Uri uri)
			{
				// PostProcessor has no access to the source URI, so how do I implement this properly?
				return false;
			}
	
			@Override
			public boolean equals(Object o)
			{
				if (this == o)
				{
					return true;
				}
				if (o == null || getClass() != o.getClass())
				{
					return false;
				}
	
				MyCacheKey that = (MyCacheKey) o;
	
				return mValue == that.mValue;
			}
	
			@Override
			public int hashCode()
			{
				return mValue;
			}
		}
	
		private static final float BLUR_RADIUS_IMAGE = 20;
		private RenderScript mRenderScript;
		private int mMyParameter;
	
		public BlurPostProcessor(RenderScript renderScript, int param)
		{
			mRenderScript = renderScript;
			mMyParameter = param;
		}
	
		@Override
		public String getName()
		{
			return BlurPostProcessor.class.getSimpleName();
		}
	
		@Override
		public void process(Bitmap bitmap)
		{
			Allocation alloc = Allocation.createFromBitmap(mRenderScript, bitmap);
			ScriptIntrinsicBlur blur = ScriptIntrinsicBlur.create(mRenderScript, Element.U8_4(mRenderScript));
			blur.setInput(alloc);
			blur.setRadius(BLUR_RADIUS_IMAGE);
			blur.forEach(alloc);
			alloc.copyTo(bitmap);
		}
	
		@Override
		public CacheKey getPostprocessorCacheKey()
		{
			// This cache key will always be the same?
			return new MyCacheKey(mMyParameter);
		}
	}

The code that makes the image request looks like this:

	imageRequestBuilder.setPostprocessor(new BlurPostProcessor(ensureRenderScript(), 0));

So this code seems to work, and my blurred images get cached. But there are two things I don't understand:

1. What is the purpose of the int parameter value mentioned in the documentation? In my implementation, I've just hard-coded it to zero but caching still works correctly? What is the point of returning a CacheKey at all if they are all identical?
2. How should I implement containsUri() correctly when PostProcessors do not have access to the source URI? Is it important to implement correctly?

**Comment by massimocarli** [comment]
Hi @jmbusby,
in order to have the Postprocessed image into cache you should just provide implementation for the getPostprocessorCacheKey() operation as you did. Are you using Drawee? The fade is something from Drawee and not related to Postprocessor. 
Anyway we'll add the cache flag to the scrolperf app in the samples as an example of this feature.
Thanks

**Comment by jmbusby** [comment]
Thanks for the response.

Yes, my views extend SimpleDraweeView. The "fading" I was referring to was I believe because the post-processed bitmaps were not cached, and when the list adapter fetched the images again with Fresco, they were regenerated by the post-processor and retriggered a fade in. Adding the caching above has fixed that problem.

Regarding my question 1 above, I am still not totally clear on the implementation of MyCacheKey. In my code, all my cache keys are equal because they are all created with the same int value, yet the caching works. Does it then follow I could just return a static MyCacheKey object in getPostprocessorCacheKey() and that would work too? Seems odd that the purpose of a cache key is to uniquely identify an object in the cache, but all my cache keys are identical!

Also, would you be able to provide an answer regarding my question 2 above about the containsUri() method on cache key, as right now I return false always from this method but I am concerned that might create bugs of some sort?

**Comment by massimocarli** [comment]
Hi @jmbusby,
the cache implementation we use for postprocessed images is the same we use for "normal" images. That's the reason we use 2 different keys and this is the reason because they should always be different. I've seen you have implemented your CacheKey implementing the interface directly but you could use SimpleCacheKey instead. Anyway, the containsUri() operation is just used in order to create predicates for cache eviction. It's useful when we want to delete all the values in cache related to the same Uri. We also use this to check if an image for a specific uri is present in cache. 
Again, your CacheKey doesn't contain the Uri but you can create one through a CacheKeyFactory implementation. It has reference to the ImageRequest which contains the Uri. 

Thanks

**Comment by jmbusby** [comment]
Thanks for the explanation, and the reference to those classes. I get it now :)
