### ISSUE TITLE
Dependency clean-up

### ISSUE THREAD

**Issue by lucas34** [facebook/fresco#1424]
Hi,

I found that each module of fresco depend on Bolts and android support-v4. But only few of them really use it. For exemple, animated-gif has this two but I cannot find the utility for the module.

Can we consider doing a dependency clean-up ?

**Comment by oprisnik** [comment]
Thanks for the info @lucas34.
If you find unnecessary dependencies, feel free to send a pull request to remove them if you want.
Otherwise, we might do a cleanup when we have some free time.

In terms of APK size, this shouldn't make a difference though. 
Both Bolts and support-v4 are used in the core imagepipeline, which is always required when you use Fresco. However, I agree that we should keep the codebase clean.

**Comment by lucas34** [comment]
Resolved in 0.14. 
Thanks guys.
