### ISSUE TITLE
App Size increasing by 1 MB

### ISSUE THREAD

**Issue by varunrramani** [facebook/fresco#1428]
Hi,

We are trying out Fresco in our App and when we build the App, the size of the app jumps by over 1 MB. Is there a way we can reduce the size of the library? We are not using any of the extra libraries just the basic one. My build.gradle looks like

    dependencies {

    //Other Dependencies

    compile 'com.facebook.fresco:fresco:0.13.0'

    }

Also if I remove Fresco and add UIL the App size increases by only 0.1 MB.

Thanks in advance!

**Comment by oprisnik** [comment]
Hi!

You should use [ProGuard](http://frescolib.org/docs/proguard.html) and you can also use [ABI splits](http://frescolib.org/docs/multiple-apks.html) to make the APK much smaller.

For example, a simple test application that I just built has 707kb without Fresco and 950 with Fresco for the armeabi-v7a architecture, so it's a bit less than 250kb in that case. For 64bit builds, the APK gets ~50kb bigger since the native libraries take up a bit more space.
