### ISSUE TITLE
Memory Keep Grown in RecyclerView

### ISSUE THREAD

**Issue by tcf150** [facebook/fresco#1458]
I have a recyclerview inside the fragment.
when i scroll and load more item, the memory will keep grown up.
Although i already release simpledraweeview controller in onViewRecycler and onViewDetached.
Memory from 130MB grow to 210MB.
i had set downsampling and resize the my image.

![loadimage](https://cloud.githubusercontent.com/assets/5754996/18271425/8fba2106-7464-11e6-8774-4acc02346cca.png)

![recycler](https://cloud.githubusercontent.com/assets/5754996/18271438/9af721e0-7464-11e6-9c39-ef81ebdb4d35.png)

![viewdetach](https://cloud.githubusercontent.com/assets/5754996/18271443/9f978956-7464-11e6-84f4-17ba54934f9c.png)

**Comment by kirwan** [comment]
It could be because the bitmaps are being retained in the memory cache.

To test that theory, you could provide an alternative `Supplier<MemoryCacheParams>` to the `ImagePipelineConfig` so that the eviction queue cannot grow bigger than 0. This is the number of bitmaps which can be held in cache, even if they are no longer used elsewhere.

You could even set the max cache size to 0 and then the cache shouldn't hold onto any bitmaps that have no other references.

**Comment by cocomikes** [comment]
Thanks. it helps me find out the solution.

**Comment by kirwan** [comment]
That's good. I've closed the issue but if you have further questions you can still reply.
