### ISSUE TITLE
How fresco renders the image without displaying to screen and listen the progress?

### ISSUE THREAD

**Issue by xiadeye** [facebook/fresco#1466]
I have struggled the problem for a long time.The situation is,I need to download a picture from network to simpleDraweeView,and transfer it to a bitmap object when it load completed.

The question is : if simpleDraweeView doesn't display to the screen,it seems not starting loading.

**Comment by oprisnik** [comment]
You can use the [image pipeline directly](http://frescolib.org/docs/using-image-pipeline.html) for this and use [subscribers](http://frescolib.org/docs/datasources-datasubscribers.html). Don't forget to [close the references](http://frescolib.org/docs/closeable-references.html) to the bitmaps once you are done so that you do not leak memory.

**Comment by xiadeye** [comment]
@oprisnik it didn't solve my problem.I don't only need the image's bitmap,I want to load the image to a view,and transfer the view(combined with other child view) to a bitmap.
your way is just get the image bitmap.
