### ISSUE TITLE
No image fade-in when loading from cache

### ISSUE THREAD

**Issue by frappes** [facebook/fresco#147]
When loading images in a RecyclerView they fade in nicely on initial load while scrolling down. When scrolling up and images are ostensibly being loaded from a cache, they do not fade in.

**Comment by tyronen** [comment]
This is deliberate. An image in cache is usually one that has been on-screen recently. It's jarring to have it fade back in.

**Comment by plamenko** [comment]
When you say "they do not fade in", do you mean they appear immediately without a fade effect, or is there a period when the image is not loaded and then it just pops in?

**Comment by frappes** [comment]
@plamenko Problem was in my code - thanks for following up though!

**Comment by jkane001** [comment]
I know this was closed, but I'm hoping to tweak the behavior a little - if the failureImage is in cache, it doesn't fade when it goes from attempting to load to the failure image. Since this (by definition) happens after the load has failed, it is more jarring. So my request is that when loading a non-"Actual" image, that it would fade to the alternate image, even if it is in cache.

**Comment by jlmcdonnell** [comment]
What about bigger images which take time to load from the cache? On my devices you can see them appearing after a delay. I think this should be enabled.
