### ISSUE TITLE
Adding fresco lib (0.10+) to gradle breaks onActivityResult

### ISSUE THREAD

**Issue by jagas** [facebook/fresco#1480]
I added fresco to my project. did not need to initialize or use any of the functionality, but places where I start activity for result to pick a photo began to return this

`FragmentActivity: Activity result delivered for unknown Fragment`

I reduced version one by one until 0.9.0 and it works fine now

**Comment by kirwan** [comment]
That's very strange and I don't see how the existence of code which is unused could result in a piece of unrelated code breaking.

I'd need more information to understand how Fresco could result in this.

- Can you provide more Logcat lines before the error and a full stack trace if there is one?
- How have you added Fresco to your project? Gradle or another way?
- Are you sure you don't use any of the Fresco APIs at all, so that removing it altogether doesn't break anything?
- Are you picking the photo using another app or do you have an activity for this?

Also, 0.10.0 is quite old so I'd be interested in knowing if the same happens with 0.14.0.

**Comment by jagas** [comment]
I started with 0.14.0 and downgraded till it started working again, so it behaves like that for me in all 0.10.0+ versions

- There is none, it just comes back with an debug message as stated before and no data about picked image and request code -1

- I am using gradle

- Thats how I tested what was causing the old behavior to break, created a different branch without fresco added it to gradle, compiled and all photo pickers in different activities started to act out

- Thats how I pick photo: 

 ```
  Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
  photoPickerIntent.setType("image/*");
  startActivityForResult(photoPickerIntent, ACTION_SELECT_PHOTO);
```


All things said, I am now trying to reproduce same behavior in a clean project and I have no luck in doing so

**Comment by kirwan** [comment]
@oprisnik has just suggested it could be due to the support library. Do you explicitly import the support library and if so, what version? Does that change in the Fresco/non-Fresco branches?

I found this Stack Overflow question where someone [suggested downgrading the support lib](http://stackoverflow.com/questions/36587428/fragmentactivity-activity-result-delivered-for-unknown-fragment), though they don't explain why that might help.

**Comment by jagas** [comment]
I am using support lib 23.1.0

I managed to reproduce the behavior. Apparently it was more complicated than I thought, I will try to explain it and share the code, maybe it will give you some insight or its just that my old code is just wrong.

Code can be found here:  https://github.com/jagas/fresco

so if you remove fresco from gradle and compile you can see that Log.e() will log your selected image, if it is with fresco it will not.

but the reason behind this that my original code had this "BaseFragment" that overrides startActivityForResult, I did that for other issue I experienced long time ago to avoid this error:

`java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode` 

and it worked fine until recent fresco lib addition. If I comment out the overridden version it all works fine.
So I could fix it for myself by removing that code, but it might bring my old problem back. Any ideas why fresco messes with ActivityCompat.startAcitivtyForResult() ?

**Comment by erikandre** [comment]
Closing due to lack updates or other reports of the issue
