### ISSUE TITLE
Does fresco work with processed files that contains a set of standard images?

### ISSUE THREAD

**Issue by ccwls3290** [facebook/fresco#1538]
I have a group of pictures, the picture is a continuous cut pictures, when in accordance with a certain rules and order to play can see the picture is a set of video sequences, I would like to use fresco to manage this part of memory,I put these pictures packaged into a binary file, may be able to modify the fresco to manage the memory, as often oom

**Comment by lambdapioneer** [comment]
Hi @ccwls3290, we have recently added the feature to add custom decoders and it sounds this would be interesting for you. However, there hasn't been a release since then, but you can start trying using the `master` branch from this repository.

See https://github.com/facebook/fresco/commit/f36cb8e80653e678cad2ad715da394d999c5dd12 for an example on how to register you own custom decoder.
