### ISSUE TITLE
Some images cannot be loaded

### ISSUE THREAD

**Issue by Pirokar** [facebook/fresco#1545]
Why it's cannot be loaded this image: http://api.kdm.initium.ru/MediaFile/Download?filePath=2\59\user_data\%D0%91%D0%B0%D0%BD%D0%BD%D0%B5%D1%80%D1%8B\Promo\Linzmaster_big_spec.png ?

**Comment by lambdapioneer** [comment]
Hi @Pirokar, the URI loads fine in our sample application. I think the following is the issue here:

The `\` is an escape character in Java strings. You most likely need to double escape its occurences: `\` -> `\\`. Alternatively, you can escape it the "uri-way" like the other special characters: `\` -> `%5C`.

**Comment by Pirokar** [comment]
no, the reason was in russian letters in uri. I've encoded it and evertythigs works fine
