### ISSUE TITLE
Disabling downsampling for a single request

### ISSUE THREAD

**Issue by rpatton** [facebook/fresco#1548]
In general I want to use downsampling but would like to disable it for a single request where I am getting an image strip that is considerably larger than allowed to render on Android. For example, the image is 40x4000 (100 frames). I'm processing the image creating an animated drawable from the 100 frames which are then rendered in sequence at 40x40. If I enable downsampling I get a 20x2000 image :( Is there any way to explicitly disable downsampling for a particular image request? I tried setting resize options but it didn't seem to help, probably because it isn't a jpg file.

**Comment by kirwan** [comment]
The reason for that sizing is that the maximum bitmap most GPUs can cope with is 2048x2048 so [we enforce that](https://github.com/facebook/fresco/blob/2cf4f9d0dfd8a690c42ed50765efbba787f9c21f/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/DownsampleUtil.java#L52) when downsampling is enabled.

A recent PR added the ability for a request's ResizeOptions to override the maximum bitmap size which should be your solution but the code I linked to above isn't checking that so this should be a simple enough fix.

If you want to send a PR (with tests for the default and overridden max sizes) that would be fantastic. Otherwise we'll get to this before the next release.

**Comment by foghina** [comment]
Fixed in 56a30cd.

**Comment by rpatton** [comment]
Thanks kirwan & foghina!
