### ISSUE TITLE
trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by sungerk** [facebook/fresco#1550]
```
    public  static  void dispaly(String url, ImageView imageView){
        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        ImageRequestBuilder builder = ImageRequestBuilder.newBuilderWithSource(getUri(url));
        ImageRequest request = builder.build();
        DataSource<CloseableReference<CloseableImage>>
                dataSource = imagePipeline.fetchDecodedImage(request, DuApplicaiton.getInstance());
        dataSource.subscribe(new BaseBitmapDataSubscriber() {
            @Override
            protected void onNewResultImpl(Bitmap bitmap) {
                imageView.setImageBitmap(bitmap);
            }

            @Override
            protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {

            }
        }, CallerThreadExecutor.getInstance());
    }
```

the code run in android 6.0.1  Exception
my phone os is cm13

but the code can run normally in other  android OS

**Comment by kirwan** [comment]
You shouldn't use a `BaseBitmapDataSubscriber` and then set the bitmap to an `ImageView` as the bitmap could be recycled any time after `onNewResultImpl()` completes.

We **strongly** recommend using a `DraweeView` instead of ImageView as it handles the lifecycle of the bitmap. If you must use an ImageView, you will have to use a `BaseDataSubscriber<CloseableReference<CloseableImage>>` and keep the `CloseableReference` until the image is no longer needed and then finally close it (for example, in `onDestroy()`.

Take a look under ["To get decoded image…" in this page of the docs](http://frescolib.org/docs/datasources-datasubscribers.html).
