### ISSUE TITLE
0.14.1版本ProgressBarImage动画不动的问题

### ISSUE THREAD

**Issue by baidongliang** [facebook/fresco#1554]
0.14.1版本 这句话是图片加载中添加一个loading, 但是升级到14版本后, 这个动画就不动, 我一个anim-list图片集合, SimpleDraweeView.getHierarchy().setProgressBarImage(R.drawable.widget_image_loading_anim, ScalingUtils.ScaleType.CENTER_INSIDE);

**Comment by aotian16** [comment]
人家可看不懂中文啊

**Comment by kirwan** [comment]
Sorry, can you repeat your question in English?

**Comment by bluef** [comment]
> I tried to add a loading progressbar with line as below. The R.drawable.widget_image_loading_anim is a anim_list pictures collection.
```
SimpleDraweeView.getHierarchy().setProgressBarImage(R.drawable.widget_image_loading_anim, ScalingUtils.ScaleType.CENTER_INSIDE);
```

> But unfortunately the animation does not work

**Comment by oprisnik** [comment]
Internally, the progress bar drawable uses `onLevelChange` to set the progress, so you have to make sure that your Drawable supports this. Otherwise, we're [setting a `ProgressBarDrawable` for our demo sample app](https://github.com/facebook/fresco/blob/b54c73ed2bbb4e2cd347f85a518da5fd5f8b20a7/samples/demo/src/main/java/com/facebook/samples/demo/MainActivity.java#L105), where this works. Can you give us an example where this does not work for the demo sample app (one of these drawables)?

**Comment by oprisnik** [comment]
I assume the problem has been resolved. Please let us know if you're still experiencing this issue.
