### ISSUE TITLE
Is Postprocessed image stored in disk cache?

### ISSUE THREAD

**Issue by Dobrygnom** [facebook/fresco#1560]
Hello, my goal is to make postprocessed image to be stored in disk cache. I am following http://frescolib.org/docs/modifying-image.html#caching-postprocessed-images notes, but it seems that it only stores it in bitmap memory cache, although original image is contained in both bitmap and disk caches.
Is there a way to make postprocessed image to be stored in disk cache?

```
        Postprocessor redMeshPostprocessor = new BasePostprocessor() { 
            @Override
            public String getName() {
                return "redMeshPostprocessor";
            }
 
            @Override
            public void process(Bitmap bitmap) {
                Log.d("LOG", "Process bitmap " + bitmap.toString());
                for (int x = 0; x < bitmap.getWidth(); x+=2) {
                    for (int y = 0; y < bitmap.getHeight(); y+=2) {
                        bitmap.setPixel(x, y, Color.RED);
                    }
                }
            }
 
            public CacheKey getPostprocessorCacheKey() {
                return new SimpleCacheKey("key");
            }
        };
 
        Uri uri = Uri.parse("https://i.mycdn.me/image?t=3&bid=835977113917&id=835977113917&plc=WEB&tkn=*0pkb8XGAqPZePrLsDyLAVNe77jI");
 
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setPostprocessor(redMeshPostprocessor)
                .build();
 
        PipelineDraweeController controller = (PipelineDraweeController)
                Fresco.newDraweeControllerBuilder()
                        .setImageRequest(request)
                        .setOldController(imageView.getController())
                        // other setters as you need
                        .build();
        imageView.setController(controller);

```

**Comment by massimocarli** [comment]
Hi @Dobrygnom,
as you experimented the Postprocessed image is not saved into the DiskCache. There we have the EncodedImage and so the image before decoding. The Postprocessor works on the DecodedImage (the Bitmap) and it's saved only into the Memory Cache. This is because the Postprocessor, which is the last producer of the pipeline,  should decorate images on the fly. If the decorated image is something you can elaborate beforehand, you could just put it on your server and use it as a normal image.  

Thanks
