### ISSUE TITLE
ReBuild The Fresco 

### ISSUE THREAD

**Issue by Leiluojun** [facebook/fresco#1564]
When I build the Fresco source using Android Studio, a .aar package will be generated under each library. But if I use the Fresco, I will have to import many .arr packag into the project. . . Can I only generate one or two .arr packages for Fresco use? If so, what do I need to do? Can you help me? Thank you...

**Comment by oprisnik** [comment]
There does not seem to be an easy way to combine .aars, see https://stackoverflow.com/questions/20700581/android-studio-how-to-package-single-aar-from-multiple-library-projects

You could import the Fresco modules to your own Android Studio project and then depend on the models instead of AARs. Then each change will be automatically picked up
