### ISSUE TITLE
long（1080x10000 +） picture become blurry

### ISSUE THREAD

**Issue by songmingwen** [facebook/fresco#1580]
When I use fresco to display a long image (1080x10000 +), the picture appears blurry
How should I use fresco to display a long graph in a list?

**Comment by oprisnik** [comment]
I guess you've enabled downsampling or resizing? Android does not allow images that large in a single Bitmap. A single 1080x10000 bitmap has around 41 MB, so that's a lot for low-end devices. Solutions:
- You can split the image up in multiple smaller images.
- There's also a discussion going on in #4 how we could decode regions on the fly. This should be possible with a custom decoder. However, the full encoded image (which should be significantly smaller though) still has to be in memory.
