### ISSUE TITLE
Prevent clearing of previous image

### ISSUE THREAD

**Issue by athornz** [facebook/fresco#1594]
Hi,

I'm attempting to implement image loading where i first load a static image, and follow up by loading a gif. I want to transition between the 2 to be seamless, but Fresco seems to clear the first image when loading the second image.

How get Fresco to simply replace the first image with the gif?

**Comment by lambdapioneer** [comment]
Hi @athornz, 

If the static image is part of the app you can set the first (static) image as the "placeholder image". The second one that needs loading would be your "actual image" (see: http://frescolib.org/docs/drawee-branches.html).

You can also set "fadeDuration" on the hierarchy in order to have a smooth transition.

If you need to load both from an external server, you can try out the code from this PR: https://github.com/facebook/fresco/pull/1328

**Comment by athornz** [comment]
Thanks for the reply. Looks like that PR (when completed) should do what I want.
