### ISSUE TITLE
How to limit network thread when using OkHttpNetworkFetcher

### ISSUE THREAD

**Issue by wstczlt** [facebook/fresco#1624]
I'm using OkHttpNetworkFetcher,  i found it use a OkHttpClient to submit network request, is there any way to limit networking thread count using fresco config? OkHttpClient can use my custom Dispatcher to limit the thread, but i think it's not a pretty implementation.

Thank you very much!

**Comment by foghina** [comment]
@facebook-github-bot stack-overflow

**Comment by foghina** [comment]
Hey @wstczlt and thanks for posting this! This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/fresco). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
