### ISSUE TITLE
Priority seems not work

### ISSUE THREAD

**Issue by wstczlt** [facebook/fresco#1625]
I have three categories of image request, one is the main image(HIGH priority), second is small image(MEDIUM priority), third is prefetched image(LOW), I test add 100 requests of them and log in RequestListener(onProducerStart). I found it doesn't execute by network producer as it's priority and seems execute as the order added in.
Could you tell me where is the code the requests get ordered, and so that I can debug, thank you very much!
I'm so sorry to trouble you so much, I am now learning the fresco library.

**Comment by foghina** [comment]
Thanks for posting this! This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/fresco). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
