### ISSUE TITLE
can I use ImageView instead of SimpleDraweeView?

### ISSUE THREAD

**Issue by wytiger** [facebook/fresco#1626]
SimpleDraweeView‘s  invasion  is strong

**Comment by foghina** [comment]
Thanks for posting this! This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/fresco). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
