### ISSUE TITLE
Switch to OkHTTP 3.6 ?

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#1648]
Hello,

Is it planned to switch to last OkHttp3 release ?

Has someone tested it with HTTP2 and Fresco?

https://github.com/square/okhttp/compare/parent-3.0.1...master

https://github.com/square/okhttp/compare/parent-3.0.1...master#files_bucket

https://github.com/facebook/fresco/blob/master/gradle.properties#L36

Thanks,

Eric

**Comment by kirwan** [comment]
If you'd like to give it a try and send a PR that would be fantastic. We don't generally use OkHttp ourselves so aren't always that quick to upgrade.

Another option would be to do what we've done with the support library and make it a "provided" dependency so that we never block anyone using Fresco from upgrading to the latest OkHttp. Do you think that would make sense?

**Comment by kirwan** [comment]
Here's an example of what I mean by making the support library a [provided dependency](https://github.com/facebook/fresco/blob/master/imagepipeline-base/build.gradle#L8), which requires client apps to specifically depend on it too.

I think it made perfect sense for the support lib which almost all apps pull in anyway. I'm curious what others think about doing the same here.

**Comment by eldk** [comment]
OK, I will have a look and come back.
Thanks.
