### ISSUE TITLE
cannot import javax.annotation.Nullable in fresco,lead to Error inflating class <unknown>

### ISSUE THREAD

**Issue by yyy000112** [facebook/fresco#1653]
cannot import javax.annotation.Nullable in fresco,lead to Error inflating class <unknown>

how to solve it

**Comment by foghina** [comment]
@facebook-github-bot stack-overflow

**Comment by foghina** [comment]
Thanks for posting this! This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/fresco). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
