### ISSUE TITLE
Can we set the position of progress bar drawable to top instead of bottom?

### ISSUE THREAD

**Issue by namchuai** [facebook/fresco#1682]
For now, the progressbar is displayed at the bottom of the loading image. I want to set it to the top. 

How can I archieved this? Thank you.

Additionally, I think that the onLevelChange is called only by the download process, not the decode process. It makes progress stuck at about  98% when the Drawee need to display gif. Do we have any solution for this?

**Comment by kirwan** [comment]
`GenericDraweeHierarchy` allows you to set your own progress bar `Drawable` so you can position it as you want within the view area.

As for the levels, it's true that the download is all that's used and that isn't ideal for animated GIFs. We actually don't generally use determinate progress bars ourselves though so I don't think we're likely to fix that soon. It's not a trivial fix because most images decode very quickly but animations can take a bit of time.

**Comment by namchuai** [comment]
Thanks for your explaination!
