### ISSUE TITLE
roundascircle does not work with GIFs starting with 1.0.0

### ISSUE THREAD

**Issue by daviswalker** [facebook/fresco#1695]
### Description

I have a static GIF and call setRoundAsCircle to round the image. In version 0.14.1 this worked correctly. Starting with 1.0.0 it does not round the image. It smells like an old issue: https://github.com/facebook/fresco/issues/188

### Reproduction

I am using a SimpleDraweeView and call getHierarchy().setRoundingParams(RoundingParams.asCircle());

### Additional Information

* Fresco version: 1.0.0 and 1.1.0
* Platform version: Tested on API 21, 23 and 24

**Comment by oprisnik** [comment]
Thank you for the bug repor!.

We've simplified the GIF decoding logic in 5ae014e00f571980c661ad553a853755d2ed37ce. This unifies GIF handling for static and animated GIFs - which breaks rounding as you've noticed since it's not supported for animated images in general.

There's a simple fix: You can force static decoding for GIFs with

```java
ImageDecodeOptions imageDecodeOptions = new ImageDecodeOptionsBuilder()
    .setForceStaticImage(true)
    .build();
ImageRequest request =ImageRequestBuilder.newBuilderWith...
    .setImageDecodeOptions(imageDecodeOptionsWithCustomDecoder)
    .build();
... // set the image request
```

**Comment by oprisnik** [comment]
Out of curiosity: Why do you use static GIFs?

**Comment by daviswalker** [comment]
Thanks for the workaround. I'll give it a try. To answer your question - we don't in general but when a user selects a photo from their library that is a GIF we don't convert it. Sounds like we should consider that...
