### ISSUE TITLE
Progressive isn't working when using OKHttpClient with HttpLoggingInterceptor

### ISSUE THREAD

**Issue by gbero** [facebook/fresco#1748]
### Description

When using OKHttpClient with HttpLoggingInterceptor progressive loading doesn't seem to work. setProgress method is never called.

### Reproduction

HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

* Fresco version: 1.3.0
* Platform version: can reproduce on 7.1.2 didn't test on other devices.

**Comment by oprisnik** [comment]
What do you mean with `setProgress` is not called? If you add a `ControllerListener`, you should see intermediate image calls for the first scans and the final image call once everything is available and has been decoded.

**Comment by gbero** [comment]
Sorry I think we misunderstood. The problem isn't about PJPEG, it's about the downloading of the image. Try adding this interceptor to the OKHttpClient used by Fresco. The method in GenericDraweeHierarchy::setProgress(float progress) is never called. Therefore the loading drawable is never called. It's probably a side effect of something but I couldn't figured it out. This is a minor issue though.

**Comment by oprisnik** [comment]
Thanks, I was able to repro the issue by modifying our Showcase sample app. No idea why this happens yet.

ShowcaseApplication.java:
```java
...
    HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
    interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

    OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .addNetworkInterceptor(interceptor)
        .build();

    ImagePipelineConfig imagePipelineConfig = OkHttpImagePipelineConfigFactory.newBuilder(this, okHttpClient)
        .setRequestListeners(listeners)
        ...
        .build();
...

**Comment by oprisnik** [comment]
I just added some logging to Fresco's [`NetworkFetchProducer`](https://github.com/facebook/fresco/blob/96636983b195cb985db36a7dc2eb7ef13f59a44b/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/NetworkFetchProducer.java#L105) that triggers progress updates. When your interceptor is added, the network fetch producer is not updated until the very end, when it suddenly gets all previous progress updates, so I guess the issue here is the listener holds back the data until the whole message is available to be able to log the whole message.

Seems like something to fix on the OkHttp side :)

If you think this is a Fresco issue, let us know and we can re-open this.

**Comment by eldk** [comment]
>Seems like something to fix on the OkHttp side :)
@gbero  : 
Maybe try it with this :  https://github.com/facebook/fresco/pull/1874
