### ISSUE TITLE
placeholderImage is still in my RAM

### ISSUE THREAD

**Issue by fanzhouyou** [facebook/fresco#1752]
when i get image from url and it shows on my screen ,but i found placeholderImage is still in my RAM. i don't know how to solve this problem

**Comment by foghina** [comment]
This is by design. If you really want to get rid of it, you can set a controller listener and remove it when the final image is set. See the docs here:

http://frescolib.org/docs/listening-download-events.html

**Comment by fanzhouyou** [comment]
i know this listener,but i do not know how to remove it ,can you tell the mothed?

**Comment by oprisnik** [comment]
`setPlaceholderImage(null)` for the hierarchy should work, see http://frescolib.org/docs/drawee-branches.html#Placeholder

**Comment by fanzhouyou** [comment]
I have tried,but it did not work. i used mat and found it still in my ram

**Comment by lambdapioneer** [comment]
@fanzhouyou the placeholder image might still be in one of our caches (e.g. the BitmapCache). We do this in order to be able to quickly re-use its bitmap without having to allocate a new one. Also if you use it then again, we can potentially skip the decoding step.

Let me know if that solved the question for you :)
