### ISSUE TITLE
could fresco get imageUrl in the callback ?

### ISSUE THREAD

**Issue by maplesnow-zsm** [facebook/fresco#1755]
i need to upload some logs when fresco load failed, but the imageurl is necessary ,could i get it in the callback ? the methods in the ControllerListener could not find the url

**Comment by foghina** [comment]
Thanks for posting this! This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/fresco). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by maplesnow-zsm** [comment]
well,thank you for the answer
