### ISSUE TITLE
Download Image and setup as linearlayout background

### ISSUE THREAD

**Issue by Anmolk22** [facebook/fresco#1790]
I want to download an image using fresco  and set it as linearlayout background. I went through the documentation and learned that it can be done using the ImagePipeline but once I change the image and restart the application crashes and after I start it second time the application seems to work fine, Please find the code below

    private void setUpPic(String coverPic) {

        Uri uri= Uri.parse(GlobalVariables.IMAGE_PREFIX+coverPic);
        final LinearLayout linearLayout= (LinearLayout) findViewById(R.id.navHeader);

        Postprocessor postprocessor = new BlurPostProcessor(this, 5);

        ImageDecodeOptions decodeOptions = ImageDecodeOptions.newBuilder()
                .build();
        ImageRequest request = ImageRequestBuilder
                .newBuilderWithSource(uri)
                .setImageDecodeOptions(decodeOptions)
                .setLocalThumbnailPreviewsEnabled(true)
                .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                .setProgressiveRenderingEnabled(false)
                .setResizeOptions(new ResizeOptions(width, height))
                .setPostprocessor(postprocessor)
                .build();

        ImagePipeline imagePipeline = Fresco.getImagePipeline();
        final DataSource<CloseableReference<CloseableImage>>
                dataSource = imagePipeline.fetchDecodedImage(request, this);

        try{
            dataSource.subscribe(new BaseBitmapDataSubscriber() {
                @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN)
                @Override
                protected void onNewResultImpl(Bitmap bitmap) {
                    assert bitmap!= null;
                        linearLayout.setBackground(new BitmapDrawable(getResources(), bitmap));
                }

                @Override
                protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {

                }
            }, UiThreadImmediateExecutorService.getInstance());

        } catch (Exception e){
            e.printStackTrace();
        }
    }

**Comment by oprisnik** [comment]
It's crashing because you have to hold on to the `CloseableReference<Bitmap> reference` until you are done displaying the image and manually call `CloseableReference.closeSafely(reference)` once you are done. If you take a look at the[ JavaDoc for `BaseBitmapDataSubscriber`](https://github.com/facebook/fresco/blob/84aeab6895f3177cee473e85656cf898112f263f/imagepipeline/src/main/java/com/facebook/imagepipeline/datasource/BaseBitmapDataSubscriber.java#L71) you see that the bitmap will be freed. That's why you see the crash.

 See http://frescolib.org/docs/using-image-pipeline.html, http://frescolib.org/docs/datasources-datasubscribers.html and http://frescolib.org/docs/closeable-references.html
