### ISSUE TITLE
Keep resized images in cache

### ISSUE THREAD

**Issue by Ncit** [facebook/fresco#183]
I need to work with small image(240,240) and save it, but I download 1080x1080 and cannot find any way to retrieve from cache folder this files.

**Comment by tyronen** [comment]
You retrieve a file from cache the same way you originally requested it. The pipeline checks for it in cache first, and resizes it according to your request.

**Comment by Ncit** [comment]
I have a lot images (1080x1080 no more than 200kb) in recyclerview. When I am asking for original image or resized directly from pipeline, it took's a lot of time for waiting async call. With path to fie it's much faster to rescale,display and send this file over http.

**Comment by tyronen** [comment]
Ah, what you are asking for is the resized image to be kept in disk cache.

I wouldn't recommend using a sync call though - you generally don't want to block the UI waiting for a disk read.

**Comment by YongzhiWang** [comment]
I also have similar question. Like Glide, it caches the resized image in the disk cache so that next time, the image could be load faster. It does not need load the full size image again.

To be more clear about the user case: I am trying to write a local photo album with a Grid view. (Only deal with the local images.) Let's say, in each row, we will show 3 images and the size of them is 200*200px. With glide, it will create a 200*200 image thumbnail and stores locally. Next time, when the same image is shown, it will load this cache rather than load the full size image and resize it again. With fresco, my understanding is that it always load the full image with sample size.  How could I configure the disk cache, so that I could store a thumbnail image locally with fresco? I do not find a way to overwrite the behaviour of disk cache, please suggest.

Thanks a lot.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tyronen** [comment]
We have recently introduced [downsampling](http://frescolib.org/docs/resizing-rotating.html#downsampling), which, although not the default yet, will mean there is no longer a resized image to be kept in cache.

**Comment by anotherdev** [comment]
Glide resizes and cache on disk based on actual view size on each device. On one device it could be 100x100 px, while other with higher resolution, 400x400px. Next time the url is loaded, no resize/downsampling need to be done anymore.

Would be great if Fresco support this.
