### ISSUE TITLE
Specifying different Image for pressed state

### ISSUE THREAD

**Issue by cody1024d** [facebook/fresco#184]
My current use-case for Fresco requires me to have a separate (in this case, darker) image for the pressed state of an image view.  We were accomplishing this via an XML selector drawable, which based on your documentation is not supported (no XML drawables are).

What would be the method of going about achieving this effect with this library?

Note: I have tried pressedStateOverlay, but this does not hide the original image, and thus, does not achieve the effect I need.

I'm not opposed to make a pull-request if that's the necessary solution.

**Comment by tyronen** [comment]
XML drawables are indeed supported. The limitation is only that they cannot be rounded.

Pressed-state overlays are, indeed, an overlay - they don't hide the original.

Thinking out loud, you might be able to get this to work with a `StateListDrawable`, but you'd need to use Java rather than XML. You would have to make use of a [DraweeHolder](http://frescolib.org/docs/writing-custom-views.html#_):

```java
DraweeHolder holder;
StateListDrawable selector = new StateListDrawable();
selector.addState(new int[] { android.R.attr.state_enabled }, holder.getTopLevelDrawable());
selector.addState(new int[] { android.R.attr.state_pressed }, pressedStateDrawable);
imageView.setImageDrawable(selector);
```

You would still have to handle attach/detach events, as explained in the docs.

**Comment by cody1024d** [comment]
Thanks for the quick reply.  I was indeed using StateListDrawables before the use of this library, so that does seem like the viable option.

Thanks for the insight, and I'll do further research into using the DraweeHolder, as opposed to the SImpleDraweeView.

**Comment by plamenko** [comment]
I'm just curious, is the pressed image just a darker variant of the original image?
Are both images network/local fetched images or are those resources bundled with the apk?

**Comment by cody1024d** [comment]
Unfortunately, the pressed image has darker regions, but the image itself isn't entirely changed.  Thus, I cannot manipulate the image itself to get the effect I am looking for.

Both images are bundled within the APK.
