### ISSUE TITLE
Infinite disk cache

### ISSUE THREAD

**Issue by Ncit** [facebook/fresco#186]
Is it possible to create disk cache with unlimited size(no more then disk size of device) and without time limit(also for unlimited time)?

**Comment by tyronen** [comment]
The disk cache does not expire anyway.

Using all the disk space is possible, but you should only do it if your app is the only app on the device. Otherwise, other apps won't be able to run if your app is hogging all the disk space.

You use the [DiskCacheConfig](http://frescolib.org/docs/configure-image-pipeline.html#configuring-the-disk-cache) class. Set a cache size equal to the physical storage space available on the device.
