### ISSUE TITLE
FileCache.getResource return null on real device but it works on AVD 

### ISSUE THREAD

**Issue by PandaQAQ** [facebook/fresco#1879]
resource return null when run on real devices, and use a lower fresco replace getMainFileCache() with getMainDiskStorageCache() it works well 
code : FileBinaryResource resource = (FileBinaryResource) Fresco.getImagePipelineFactory()
                    .getMainFileCache()
                    .getResource(new SimpleCacheKey(uri.toString()));
device info : huawei honor 8 base on Android N

**Comment by kirwan** [comment]
Writing files to disk is handled in a separate thread so it's quite possible for an image request to complete but the file not yet be available from the cache.

My guess is you're just being luckier in the race on your emulator than your device.

Instead of querying cache directly, I'd recommend requesting the encoded image from the pipeline. See the [To get encoded image…](http://frescolib.org/docs/datasources-datasubscribers.html#to-get-encoded-image) section in the docs. Request that with the original image request and the multiplexing within Fresco will ensure only one network request is used.
