### ISSUE TITLE
How to display bitmap object by DraweeView?

### ISSUE THREAD

**Issue by rhettor** [facebook/fresco#1897]
I found `DraweeView#setImageDrawable(Bitmap bm)` method is deprecated! 
if I want to display bitmap object, How to do it by `setController(DraweeController)` ?

**Comment by erikandre** [comment]
Hi @rhettor,

If you just want to display a Bitmap then using an ImageView might be easier.
Is there a particular reason why you want to use DraweeView?

**Comment by rhettor** [comment]
@erikandre

Just example. I have photo filter util to modify brightness or others by user,  the util just return bitmap object. First, It show online or local photo, and next drag progressBar to change brightness, finally real-time show this changed.
So, `DraweeView` want to display bitmap object.

**Comment by erikandre** [comment]
OK, thanks for the explanation @rhettor 

Since DraweeView is not very well suited for that use case you might want to try a workaround using 2 views:

1st view is a SimpleDraweeView that you use to load and display online/local photo
2nd view is an ImageView that you use to display the modified Bitmap

Once the user changes the brightness you could switched between view 1 & 2
