### ISSUE TITLE
Hello,i use setDownsampleEnabled() and ResizeOptions() to gif,but it is invalid.So what can i do to solve it.Thanks.

### ISSUE THREAD

**Issue by lemon-zzz** [facebook/fresco#1928]
We use GitHub Issues for bugs.

If you have a non-bug question, please ask on Stack Overflow: http://stackoverflow.com/questions/tagged/fresco

--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

### Reproduction

[FILL THIS OUT: How can we reproduce the bug? Provide URLs to relevant images if possible, or a sample project.]

### Solution

[OPTIONAL: Do you know what needs to be done to address this issue? Ideally, provide a pull request which fixes this issue.]

### Additional Information

* Fresco version: [FILL THIS OUT]
* Platform version: [FILL THIS OUT: specific to a particular Android version? Device?]

**Comment by lambdapioneer** [comment]
Hi @lemon-zzz, for GIF images we do not support `setDownsampleEnabled()` and `ResizeOption`s. This is because we don't have the primitives for efficient resizing of GIF images.

Hope this information is helpful and answers your question. Otherwise, please feel free to comment here and I'll reopen the issue.

**Comment by lemon-zzz** [comment]
Thanks anyway.
