### ISSUE TITLE
 Post-process caching is not always successful

### ISSUE THREAD

**Issue by babyblue1314** [facebook/fresco#1978]
### Description
I am using RecyclerView to show images that are ciphered on our server, so post-process should be done before displaying. In order to eliminate the fade-in animation, I need to cache the post-processed images. However, the post-process caching is not always successful. 

By using Fresco's logcat, I found that:
1. when post-process caching is successful, it shows that "PostprocessedBitmapMemoryCacheProducer ... cached_value_found=true";
2.  when post-process caching is not successful, it shows that "PostprocessedBitmapMemoryCacheProducer  ... cached_value_found=false ... EncodedMemoryCacheProducer ... cached_value_found=true";

By using ImageCacheStatsTracker, I found that:
1. when post-process caching is successful, onBitmapCacheHit is executed, the cachekey is sth like "sourceUrl_resizeOptions_rotationOptions_imageDecodeOptions_postprocessorCacheKey_postprocessorName_-1663234999";
2. when post-process caching is not successful, onBitmapCacheHit is also executed, but the cachekey is sth like "sourceUrl_resizeOptions_rotationOptions_imageDecodeOptions_null_null_59364978", or just sth like "sourceUrl"; 
(PS: I can assure that sourceUrl above is the same.)

As seen from ImageCacheStatsTracker, the cachekeys are different: "postprocessorCacheKey" and "postprocessorName" are null in 2, or cachekey in 2 only contains the sourceUrl. Additional, when I printed the cachekeys before fetching post-processed bitmap to cache and loading image to simpleDraweeView, they're just sth like 1. I believe the difference caused this issue.

So, I wonder why this happens and how to fix it.

### The relevant code is:
1) FetchPostProcessedBitmapToCache
<pre><code>DecipherPostProcessor mDcipherPostProcessor = new DecipherPostProcessor(url);
ImageDecodeOptions mImageDecodeOptions = new ImageDecodeOptions(ImageDecodeOptions.newBuilder().setBitmapConfig(Bitmap.Config.RGB_565));
ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url))
                      .setPostprocessor(mDcipherPostProcessor)
                      .setRotationOptions(RotationOptions.autoRotate())
                      .setProgressiveRenderingEnabled(true)
                      .setImageDecodeOptions(mImageDecodeOptions)
                      .setResizeOptions(ResizeOptions.forDimensions(400, 800))
                      .build();
Fresco.getImagePipeline().fetchDecodedImage(imageRequest, null);</code></pre>
     
      

2) LoadImage
<pre><code>DecipherPostProcessor mDcipherPostProcessor = new DecipherPostProcessor(url);
ImageDecodeOptions mImageDecodeOptions = new ImageDecodeOptions(ImageDecodeOptions.newBuilder().setBitmapConfig(Bitmap.Config.RGB_565));
ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url))
                 .setPostprocessor(mDcipherPostProcessor)
                 .setRotationOptions(RotationOptions.autoRotate())
                 .setProgressiveRenderingEnabled(true)
                 .setImageDecodeOptions(mImageDecodeOptions)
                 .setResizeOptions(ResizeOptions.forDimensions(400, 800))
                 .build();
DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                 .setOldController(simpleDraweeView.getController())
                 .setImageRequest(imageRequest)
                 .build();
simpleDraweeView.setController(draweeController);</pre></code>

3) DecipherPostProcessor
<pre><code>public class DecipherPostProcessor extends BasePostprocessor {
    private String mUrl;

    public DecipherPostProcessor(String url) {
        this.mUrl = url;
    }

    @Override
    public String getName() {
        return "decipherPostProcessor";
    }

    @Override
    public void process(Bitmap bitmap) {
        ImgCipherUtil imgcipher = new ImgCipherUtil();
        imgcipher.Decipher(mUrl, null, bitmap, true);
    }

    @javax.annotation.Nullable
    @Override
    public CacheKey getPostprocessorCacheKey() {
        return new SimpleCacheKey("0");
    }
}</pre></code>

### Additional Information
* Fresco version: 1.5.0
* Platform version: Android 5.1.1, REDMI NOTE 3

**Comment by oprisnik** [comment]
I believe the issue here could be that Fresco caches both the original image and the postprocessed image in memory cache. If for example the postprocessed image gets evicted from the cache (which I guess happens in your example), we'll have a hit on the original image and then apply the postprocessor and then cache the postprocessed image.
The postprocessed image will currently not be cached to the disk. If you prepare a lot of images ahead of time, you'll find that on devices with low memory, you can run into the situation where you'd prepare too many images, which means that the least recently used ones (which are now the ones that are about to be displayed) get evicted, which means you run into the situation that you've described.

However, I think that in your case, having a custom decoder would be the correct way? I don't know how your encryption works (what the original bitmap looks like), but you can just add a (globalZ) custom decoder that is able to decode the image stream you get from the network directly - which is way better for memory since you don't have to cache both versions. This should then also help with having more images cached.
A simple example for a custom color decoder can be found here: https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/color/ColorImageExample.java
