### ISSUE TITLE
Bitmap limit is hardcoded to 384

### ISSUE THREAD

**Issue by EMIN3M1986** [facebook/fresco#1980]
Hi. I'm using fresco to load a lot of stickers.
Until version number 14 there is no any problem. In 14 and above always on pre lollipop version this exception happened and app crashed.
I set maximum number of cache in fresco configuration. 
     com.facebook.imagepipeline.common.TooManyBitmapsException

**Comment by foghina** [comment]
Are the stickers animated (gif / webp)?

If not, it's probably just a matter of either increasing the memory cache size (which you can do when configuring the pipeline), or more aggressively recycling DraweeViews. What are you using to display stickers, ScrollView or List/RecyclerView?

**Comment by EMIN3M1986** [comment]
Yes I use some animated (gif) and png Stickers in RecyclerView. 
I set cache on maximum.

**Comment by EMIN3M1986** [comment]
This is the Error Message :
com.facebook.imagepipeline.common.TooManyBitmapsException: Attempted to pin a bitmap of size 65536 bytes. The current pool count is 384, the current pool size is 45220368 bytes. The current pool max count is 384, the current pool max size is 100663296 bytes.

**Comment by EMIN3M1986** [comment]
Nobody ?

**Comment by EMIN3M1986** [comment]
It seems nobody knows the issue and I obligate to use glide instead.

**Comment by foghina** [comment]
We have this issue internally to some degree as well. In our case the fix was to use `forceStaticImage` in the decode options so that we only show the first frame of the gif in the RecyclerView. You can then implement a tap-to-play feature. Showing many GIFs in a grid/list view is going to be hard with any image library.

You can also look into using videos instead.

> In 14 and above

Do you mean version `0.14`? That is very old. Have you tried with something more recent, like `1.7.1`?

**Comment by EMIN3M1986** [comment]
I remove all gifs and load just png. Even in version 1.8.0 there is this problem too. 
Whay are you put limitation ?

**Comment by foghina** [comment]
So I think in v1.4.0 (is this what you're using?) we switched from having a separate memory cache for GIF frames to using the main one. This is good generally as it reduces the overall memory footprint (and OOMs) of Fresco by evicting other bitmaps in favor of animation frames, but it does also lead to this exception.

@oprisnik since you made this change, do you know if there is a way around this exception? Perhaps increasing the default bitmap pool size? Or configuring the frame prefetching differently?

**Comment by oprisnik** [comment]
The limit is hardcoded to 384 at the moment (https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/BitmapCounterProvider.java#L26) but we should re-evaluate that.

**Comment by robinxb** [comment]
We are facing the same issue that reaching the 384 limitation. Is there any solution we can bypass this exception ?

**Comment by wangbin0802** [comment]
I don't know why the official still not solve this problem? This will cause lots of crash in my app.

**Comment by tgithubc** [comment]
@robinxb  
you can see https://github.com/facebook/fresco/issues/213 
There has my answer in the article, I hope I can help you.

**Comment by oprisnik** [comment]
We should make this configurable.

**Comment by defHLT** [comment]
This is now an option 3ccf021877571cc66c1cf28ecc82788f83579ad3

**Comment by huopochuan** [comment]
> Are the stickers animated (gif / webp)?
> 
> If not, it's probably just a matter of either increasing the memory cache size (which you can do when configuring the pipeline), or more aggressively recycling DraweeViews. What are you using to display stickers, ScrollView or List/RecyclerView?

use RecyclerView

**Comment by huopochuan** [comment]
if bitmap over 384, it do not recycle/release?

**Comment by defHLT** [comment]
@huopochuan Sorry, not sure I understand your question.
