### ISSUE TITLE
CacheKey doesn't contains Postprocessor when submit a ImageRequest

### ISSUE THREAD

**Issue by jungletian** [facebook/fresco#2007]
### Description

When submit a ImageRequest with PostProcessor, BitmapMemoryCacheProducer$produceResults() should use `getPostprocessedBitmapCacheKey` method. Otherwise the cached bitmap key is different from the `mCacheKey` of PipelineDraweeController.class

### Solution

use `getPostprocessedBitmapCacheKey` replace `getBitmapCacheKey` in BitmapMemoryCacheProducer$produceResults()

**Comment by zmroczek** [comment]
This issue isn't valid since the logic for caching post-processed images is included in PostProcessorProducer (more info in #2008).

**Comment by zmroczek** [comment]
This PR changes the current logic of caching post-processed images. This issue isn't valid because in order to cache the post-processor results you need to implement the getPostprocessorCacheKey() method (see docs http://frescolib.org/docs/modifying-image.html#caching-post-processor-results) which is used in PostprocessorProducer.

For postprocessors that we decide not to require caching the image to be processed is still taken from cache with a cache key returned from getBitmapCacheKey() method.
