### ISSUE TITLE
Android Oreo - can't load some PNG - BitmapFactory: bitmap marked for reuse (3944728 bytes) can't fit new bitmap (7889456 bytes)

### ISSUE THREAD

**Issue by scdc** [facebook/fresco#2021]
Fresco can't load some PNG on OREO. We've got the followling warning:

W/BitmapFactory: bitmap marked for reuse (3944728 bytes) can't fit new bitmap (7889456 bytes)
The code to reproduce the bug:

```Kotlin 
override fun onCreate(savedInstanceState: Bundle?) {
        Fresco.initialize(this)
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val uri = Uri.parse("https://kyashu.aquafadas.com/wsapi/KyashuDownload.php?service=KS-AvePublishing&error=404&keepaspect=1&uselength=0&ratio_filter=0&width=1080&height=394&format=png&upscale=1&stickyRatio=desc&operation=fill&ids=5281064;5281065;5281066&version=0")
        val draweeView = findViewById<View>(R.id.my_image_view) as SimpleDraweeView
        draweeView.setImageURI(uri, this)

    }
```
Steps to reproduce:
- launch the sample code on android Nougat 7.1  and before, it works
- launch the sample code on android Oreo the PNG is not loaded
- Expected result same code should work on Oreo and Nougat

Device: One Plus 5 
Fresco Version: 1.7.1

**Comment by oprisnik** [comment]
Thanks for reporting this issue.
Android Oreo added support for wide color gamut images and Fresco does not fully support wide color gamut yet. I've recently implemented a workaround so that they are at least rendered (albeit less efficiently), 4a64df0099776be6bb1e229a274526e1d5c54df3

The next release will include the fix. Proper support will be added at some point in the future. Pull requests are welcome :)
