### ISSUE TITLE
The cpu usage is high when I use webp 

### ISSUE THREAD

**Issue by eaggle** [facebook/fresco#2035]
=============
following is the initialize code

//内存配置
        final MemoryCacheParams bitmapCacheParams = new MemoryCacheParams(
                (MAX_MEMORY_CACHE_SIZE * ByteConstants.MB),// 内存缓存中总图片的最大大小,以字节为单位。
                512,// 内存缓存中图片的最大数量。
                MAX_MEMORY_CACHE_SIZE * ByteConstants.MB,// 内存缓存中准备清除但尚未被删除的总图片的最大大小,以字节为单位。
                Integer.MAX_VALUE,// 内存缓存中准备清除的总图片的最大数量。
                Integer.MAX_VALUE);// 内存缓存中单个图片的最大大小。

        //修改内存图片缓存数量，空间策略
        Supplier<MemoryCacheParams> mSupplierMemoryCacheParams = new Supplier<MemoryCacheParams>() {
            @Override
            public MemoryCacheParams get() {
                return bitmapCacheParams;
            }
        };

ImagePipelineConfig.Builder builder = ImagePipelineConfig.newBuilder(this)
                .setDownsampleEnabled(true)
                .setBitmapMemoryCacheParamsSupplier(mSupplierMemoryCacheParams)
                .setMemoryTrimmableRegistry(NoOpMemoryTrimmableRegistry.getInstance())
                .setResizeAndRotateEnabledForNetwork(true);
        Fresco.initialize(this, builder.build());

===============
follow is the usage of SimpleDraweeView

public EasyHolder<M> setWebPImageURI(int viewId, Uri uri, int width, int height, Drawable defaultDraw) {
        SimpleDraweeView draweeView = getView(viewId);

        if (defaultDraw != null) {
            GenericDraweeHierarchy hierarchy = draweeView.getHierarchy();
            hierarchy.setPlaceholderImage(defaultDraw, ScalingUtils.ScaleType.CENTER);
        }
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(new ResizeOptions(width, height))
                .build();
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request)
                .setAutoPlayAnimations(true)
                .build();
        draweeView.setController(controller);

        return this;
    }

=============
<img width="1450" alt="qqq" src="https://user-images.githubusercontent.com/11845292/35438959-c49da858-02d3-11e8-9a02-a874e3dc3945.png">

**Comment by eaggle** [comment]
seams the FrescoDecodeExe is running all the time when the webp is animating.

**Comment by dmitry-voronkevich** [comment]
Thanks you for reporting this @eaggle. Does it behave differently for gif's?

**Comment by eaggle** [comment]
@dmitry-voronkevich gif is no different, also high cpu usage.
![image](https://user-images.githubusercontent.com/11845292/35566318-eabdb8d6-05fb-11e8-8cda-1f0cb945fbc8.png)

**Comment by eaggle** [comment]
I play 9 gif in my app with the same url (http://storage.slide.news.sina.com.cn/slidenews/77_ori/2018_05/74766_812099_715784.gif).

![image](https://user-images.githubusercontent.com/11845292/35566370-1ebf7174-05fc-11e8-8949-d86f2008a31c.png)

**Comment by oprisnik** [comment]
Hi @eaggle. Android does not natively support GIFs and animated WebPs. Fresco includes custom decoders that make use of native C/C++ libraries to add that functionality and manually create Bitmap frames - which is not hardware accelerated.
Also, constantly updating all views with the bitmap frames requires the view to be invalidated, the next frame to be loaded from cache, the drawable updated, the new bitmap drawn and next frames prepared ahead of time so that they are ready - which explains your CPU usage.

I'm afraid that at the moment there's not a lot that you can do. You can customize the animation so only selected animation frames are played (and drop the rest) or have some GIFs tap-to-play and you should ensure that the memory cache is adequately sized. If that is not the case (e.g. imagine the cache is 0, you cannot cache any frames and always have to re-decode all the frames).

For your GIF URL that you posted above:
It has 60 frames, each of them 170x121, 8 bit.
This means that all frames for 1 GIF take up ~ 4.7 MB, for 9 GIFs this would be ~42 MB.

If you have any suggestions on how to improve this, please let us know and submit a pull request!
To experiment with different decoders, you can add a custom decoder, see http://frescolib.org/docs/customizing-image-formats.html
