### ISSUE TITLE
Regarding Loading of Google Drive Shared image through Fresco Lib

### ISSUE THREAD

**Issue by joney123** [facebook/fresco#2052]
Hi Team,

I am new to this . I need your help to load a link that was shared in Google Drive in Android.Sample code can be appreciated.

https://drive.google.com/file/d/1Fk927RznY5WY4AWDmRihPJbKtSZynCct/view

Joney

**Comment by joney123** [comment]
Log was shown as below 
ProgressiveDecoder: unknown image format, {uri: https://drive.google.com/file/d/1Fk927RznY5WY4AWDmRihPJbKtSZynCct/view?usp=sharing
                                                                                       , firstEncodedBytes: 3C21444F435459504520, length: 124663}

**Comment by oprisnik** [comment]
The link that you are passing is not to a photo but to a webpage that renders a photo as part of it and Fresco cannot parse that since it's not an image.

The URI that you are passing needs to be an image, so I suppose there is a Google Drive API / SDK that lets you do that, maybe https://developers.google.com/drive/ can help.
Since this question is not related to Fresco but to Google Drive, I'd suggest posting on StackOverflow or looking at the Google Drive APIs / SDK.
