### ISSUE TITLE
Add option to always fade in image, even if cached

### ISSUE THREAD

**Issue by alexbirkett** [facebook/fresco#2138]
### Description

`fresco:fadeDuration` works the first time image url is set but when the image is loaded from the cache `fresco:fadeDuration` is ignored.

### Reproduction

```    
// fade animation works
imageView.setImageURI("http://yourdomain.com/image1.jpg")
// fade animation works
imageView.setImageURI("http://yourdomain.com/image2.jpg")
// fade animation fails
imageView.setImageURI("http://yourdomain.com/image1.jpg")
```

### Solution

I suspect this has something to do with  `final boolean wasImmediate = mDataSource.hasResult();` in  `AbstractDraweeController.submitRequest()`

### Additional Information

* Fresco version: 1.9.0
* Platform version:  8.1 (I assume all other platforms too)

**Comment by oprisnik** [comment]
This is the intended behavior since usually you only want to fade the image in if it takes longer to download (i.e. fade from placeholder to image). However, if the image is already downloaded, you'd just want to display it immediately.

It would be possible to add an additional flag somewhere to always fade in, but right now this is not supported. Feel free to submit a pull request.

**Comment by erikandre** [comment]
@alexbirkett , if you need this behaviour I would recommend disabling Fresco's fading and instead perform a view animation once the image is loaded to achieve the desired fade-in.
