### ISSUE TITLE
ImageCacheStatsTracker's onDiskCacheHit should provide the cache key param

### ISSUE THREAD

**Issue by JuniperPhoton** [facebook/fresco#2207]
### Description

ImageCacheStatsTracker is used for tracking caching status like disk or encoded memory.

The `onBitmapCacheHit`, `onMemoryCacheHit` and `onStagingAreaHit` methods all provide the cache key param, from which we can get the request url.

However, the `onDiskCacheHit` method does not provide the cache key param. Are there any reasons not doing it?

Currently, there is a workaround to do so:

> Set a `CacheEventListener` to the disk config on configuring the image pipeline, then do the record inside. It worked, but I think it's not great.

**Comment by jokermonn** [comment]
I think both `*Miss()` method should also provide the cache key, because it seems no way to judge which picture call `*Miss()` method. One picture is not hited by memory/bitmap/staging area, but it hited by disk cache, and then I think it's hited by cache. if there are many pics,  `onMemoryCacheMiss()`/`onBitmapCacheMiss()`/`onStagingAreaMiss()` and `onDiskCacheHit()` will be called many times, and how I judge one picture is hited in the end or miss?

**Comment by JuniperPhoton** [comment]
At first I think that may a historical reason: keep the interface unchanged so that the apps using the latest Fresco won't break in build. But if this should be improved, I can also help changing the code to fix this.

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@defHLT Can I work on this?

**Comment by defHLT** [comment]
I think we can make this change. @JuniperPhoton @MONIKA-KUMAR-JETHANI help would be appreciated.

**Comment by JuniperPhoton** [comment]
@defHLT Here is the PR: https://github.com/facebook/fresco/pull/2210

**Comment by defHLT** [comment]
Merged. Thanks for your help!
