### ISSUE TITLE
Memory increases rapdly when there are webps(AnimatedDrawable) in RecyclerView. how to solve the problem?

### ISSUE THREAD

**Issue by qhyuan1992** [facebook/fresco#2208]
version 1.8.1 or above
 
Memory increase rapidly when I use Webps in RecyclerView.
I have a webp in each item, each webp has about 50 frames and has a size of 150*56. I find that 50 Bitmaps are decoded into memory for each webp, each webp has 50 bitmaps, this is unbelievable.
there are 100 bitmaps in memory when i show two webps  both of which are the same.
also when i scroll out or in to screen, each webp are decoded into memory once again.

my question are as follows:
1.why use cache strategy CACHING_STRATEGY_FRESCO_CACHE_NO_REUSING(2) for default, which leads to all the frame are decoded to memory.

2.can not both of the two webps use the same cache althrough they may be loaded from the same request(there request params are the same), also the same file in fact?  From the `equals` of `FrameKey` i see it that.
```java
@Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof FrameKey) {
        FrameKey that = (FrameKey) o;
        return this.mImageCacheKey == that.mImageCacheKey &&
            this.mFrameIndex == that.mFrameIndex;
      }
      return false;
    }
```

**Comment by oprisnik** [comment]
If there is memory available, Fresco makes use of that memory. It would be a waste if you set up Fresco to utilize x MB and then only use x/100 MB for animated GIFs.

The reason why we don't reuse the bitmaps per default is related to that. If we have the memory we use it instead of decoding the same frame over and over again, which wastes a lot of CPU time.

2: That seems like a bug, cache keys should use a proper equals check. I'll fix that, thanks.
