### ISSUE TITLE
Gif image display frequently triggers garbage collector(gc), the higher the frame rate of gif is, the more obvious

### ISSUE THREAD

**Issue by xSharkM** [facebook/fresco#2215]
### Description

In a scrollable view, such as RecyclerView. While the gif image is displayed, sliding the RecyclerView will not feel smooth. As the frame rate of the gif is larger, the more obvious.I use Android Profiler to monitor memory find frequently triggers garbage collector(GC).Will seize the main thread time CPU slice.

### Reproduction

Place the gif image in an item in the RecyclerView. After the gif image is loaded, slide the RecyclerView.

### Additional Information
Fresco version: 1.10.0
gif image url: https://img2.tapimg.com/bbcode/images/1e3d243482e51c298d789f9a9c15cd66.gif?imageView2/2/w/984/interlace/1/ignore-error/1

**Comment by oprisnik** [comment]
The GIF that you're linking is 790x742 pixels and has 80 frames. Each bitmap frame requires 2.2 MB, which means in total this GIF alone requires 180 MB of RAM for all frames in ~1 second (animation duration). Fresco's bitmap memory cache is probably not going to be able to keep all frames in memory if you have a grid of huge GIFs similar to the one that you've linked (e.g. a 3x3 grid), which would require 1600 MB to keep all frames separately in memory, so we have to re-decode.

An alternative would be to either limit the frame rate by supplying a custom animation backend that for example cuts the number of frames in half. Otherwise, not playing all GIFs all the time or supplying smaller GIFs should also help here. 
Fresco currently does not support GIF resizing, the feature request for this is #1975.

**Comment by xSharkM** [comment]
thank you!
