### ISSUE TITLE
Memory usage increases after Fresco implementation 

### ISSUE THREAD

**Issue by Androidraja** [facebook/fresco#2216]
### Description
I'm using glide in my project but facing memory usage 120-140mb. Then I decide to replace it by Fresco because as per description Fresco using system cache
Then I replace by Fresco memory usage inceesed to 240-270mb

### Reproduction

Create recycler adapter with image using Glide and check memory usage. Then replace by Fresco and compare 

* Fresco version: [1.10.0]
* Platform version: 5.0 to 8.1

**Comment by oprisnik** [comment]
Fresco has a comparison sample app: https://github.com/facebook/fresco/tree/master/samples/comparison

For newer Android versions, Fresco can't use ashmem any more since the API has been removed. So both Fresco and Glide are making use of Java bitmaps. If set up similarly (see comparison app), memory consumption of both is quite similar. I suppose that you are for example resizing images differently or have different memory cache parameters set where Fresco has a bigger memory cache.
