### ISSUE TITLE
large gif problem

### ISSUE THREAD

**Issue by didixyy** [facebook/fresco#2278]
when i load a large gif in demo app decoder with movie decoder ,it doesn't work，the picture looks blurry.native decoder is work.
This is url(https://img2.tapimg.com/album/etag/FqOcaqDH1kQ16BuYuDinyhQkV_io.jpg?imageView2/2/w/984/interlace/1/ignore-error/1)
![screenshot_20190122-170505_fresco showcase](https://user-images.githubusercontent.com/17633836/51524485-1d17a900-1e69-11e9-922b-79a10114088b.jpg)
![screenshot_20190122-170449_fresco showcase](https://user-images.githubusercontent.com/17633836/51524491-230d8a00-1e69-11e9-8ae6-a038df894376.jpg)

* Fresco version: [1.11.0]
* Platform version: [28]

**Comment by oprisnik** [comment]
Thanks for the info @didixyy. We're still evaluating the Movie decoder and it seems that it doesn't work for this particular use case. My first guess would be that this cannot be fixed since the Movie class is baked into the Android system, but we'll investigate. For now, please use the native GIF version instead.

**Comment by didixyy** [comment]
> Can you post the GIF somewhere else @didixyy ? I always get a "403 Forbidden".
ok,  i upload the gif in the google 
https://photos.google.com/share/AF1QipNCPNAHcDh3ZzonQ5ushrZIZ-KCspAnq5BzkDtZlZVdf6td8EsFGHJCHOy_UBrqeQ/photo/AF1QipOlN3K_EY54oX1lCJIqVyClhRYJaFB_5ZuNGwHB?key=OThlczZQZndYV3E0ZW96RE93UUlyTHV0RV8xVDFR

**Comment by erikandre** [comment]
Thanks for upload the gif!
Most likely, the Android platform gif decoder (used by the movie decoder) has a limit on how large the output frame is, and since your gif is very tall I believe it goes above this causing it to be scaled down (making it blurry).

Your best option is to follow oprisniks suggestion and use the native gif decoder instead.
