### ISSUE TITLE
simpleDraweeView.getController().getAnimatable()==null

### ISSUE THREAD

**Issue by songsong0218** [facebook/fresco#2325]
Animatable animatable=simpleDraweeView.getController().getAnimatable()
animatable always is null  ，But my webp is loading successfully,How can I make an animatable not null?

**Comment by erikandre** [comment]
Hi @songsong0218 

Have you tried using a listener to access the animatable after the image is loaded?
https://frescolib.org/docs/listening-to-events.html

**Comment by songsong0218** [comment]
@erikandre  There are a lot of gif images in my recycleview, and there are also png images. I need to dynamically play a gif or stop. If there is only one gif this is a good choice

**Comment by oprisnik** [comment]
The animatable will be null for non-animated images, so this is expected. If you're loading an animated image, `simpleDraweeView.getController().getAnimatable()` will return null as long as the image has not been loaded. That's why having a listener is a better approach.

**Comment by KimiChiu** [comment]
Having same issue here. It's working like a charm in a recycler view.
But if I put the `SimpleDraweeView` in the layout of the activity and load images later, the animatable will always be null.
`setAutoPlayAnimations(true)` is playing well too.
But I like it to be stopped at first, so I'm using `setAutoPlayAnimations(false)`.
I'm sure the gif is loaded, because I wait for 5 minutes and it still returns null.
