### ISSUE TITLE
Incompatibility with AndroidX

### ISSUE THREAD

**Issue by tgpetrov** [facebook/fresco#2330]
### Description
In a project using the AndroidX library and Fresco, I need to explicitly enable the jetifier to build the project.

### Solution
Release a new version of the Fresco lib that targets AndroidX.

I see the code is already migrated, do you have a planned release date that will include the AndroidX support?

**Comment by oprisnik** [comment]
Right now, we don't want to force everybody using Fresco to migrate their whole app to AndroidX. Fresco already supports AndroidX, as you mentioned you can always use Jetifier - but you cannot go back once we release AndroidX versions.

At some point, we'll start publishing AndroidX releases, but we're not sure yet when (since we have to bump the major version for this).

**Comment by oprisnik** [comment]
Fresco 2.0.0 is now available that requires AndroidX: https://github.com/facebook/fresco/releases/tag/v2.0.0

For non-AndroidX builds, please continue using v1.14.2

**Comment by eygraber** [comment]
@oprisnik Fresco 2.0.0 has a transient dependency on the support libs through stetho, which prevents turning off jetifier.

**Comment by AsiamCn** [comment]
@oprisnik I dowloaded v1.14.2, it still depends on androidx..
![image](https://user-images.githubusercontent.com/10176630/65585804-a6155000-dfb5-11e9-9b25-29f1f79831f4.png)

**Comment by oprisnik** [comment]
Sorry, seems that 1.13.0 is the one to go, I'll update the comment above.
