### ISSUE TITLE
BaseBitmapDataSubscriber Leak

### ISSUE THREAD

**Issue by Awent** [facebook/fresco#2530]
when I use BaseBitmapDataSubscriber in my PagerAdapter, the activity is closed when the photo is loading ,then I got the LeakCanary leak:

**fresco version:2.2.0**

**code:**

```
dataSource.subscribe(new BaseBitmapDataSubscriber() {

                                     @Override
                                     public void onNewResultImpl(@Nullable Bitmap bitmap) {
                                         // You can use the bitmap in only limited ways
                                           }

                                     @Override
                                     public void onFailureImpl(DataSource dataSource) {
                                         // No cleanup required here.
                                     }
                                 },
                    CallerThreadExecutor.getInstance()); 
```

**Leak detail:**
![fresco leak](https://user-images.githubusercontent.com/13899216/90894175-c7173880-e3f2-11ea-9620-fe6f7fa5f6c9.jpeg)

**Comment by defHLT** [comment]
Hi, thanks for the report. 

A datasource will keep a reference to datasubscriber you provided. A datasource will clean up this reference automatically when either a) the final image is downloaded, or b) the error occurred. 

You can also force clean up by closing datasource. Since you are using datasources manually (and not using UI components) you should close the datasource when the user leaves activity.
