### ISSUE TITLE
okhttp transport alternative

### ISSUE THREAD

**Issue by theromis** [facebook/fresco#2536]
After latest `kotlin` upgrade `okhttp:3.12.12` for `ktor` not an option any more. https://github.com/square/okhttp/issues/6249

I switched my `API21+` builds to `ktor-cio` but still can't cut `okhttp` deps because of fresco, is there an option or potential roadmap to have "transport plugins" to be able change `okhttp` to something else (I'd like to switch to `ktor-cio`)?

**Comment by oprisnik** [comment]
Hi!

Fresco already supports different network layers, you just have to implement a custom network fetcher: https://frescolib.org/docs/using-other-network-layers.html
Feel free to implement a ktor plugin for Fresco by implementing our

Examples for OkHttp and Volley:
https://github.com/facebook/fresco/tree/master/imagepipeline-backends

If you want, feel free to submit a pull request that adds a new Gradle module so that others can benefit as well :)
