### ISSUE TITLE
FlipperImageTracker class not found while building an AAR file

### ISSUE THREAD

**Issue by michalchudziak** [facebook/fresco#2556]
### Description

Hey,

I'm building AAR file with some React Native modules packaged inside. I wanted to embed Flipper packages to debug flavour of this AAR in order to facilitate debugging. Everything's good in compile process, but when I try to instantiate `FrescoFlipperPlugin`, runtime error is being thrown. `FlipperImageTracker` is not found.

I've inspected the contents of generated `classes.jar` and only 2 classes are available:
![image](https://user-images.githubusercontent.com/7837457/97905137-ca5b6880-1d41-11eb-98b2-59d8ef7eeefc.png)

Imports cannot be resolved in Android Studio as well:
![image](https://user-images.githubusercontent.com/7837457/97904635-14901a00-1d41-11eb-921b-1f41a8ef695c.png)

Currently I'm using Fresco `2.0.0`, but the same issue exist for versions `2.2.0` and `2.3.0`.

### Reproduction

`./gradlew bundleDebugAar` on React Native 0.62.X app with Flipper integrated.

### Additional Information

* Fresco version: 2.X.X

**Comment by oprisnik** [comment]
Hey! This is interesting, the classes should be part of the artifact. Are you including fresco:flipper via Gradle? That's the one that has the classes

Otherwise, could it be that ProGuard is not properly working?
We do have a ProGuard config shipped with Fresco https://github.com/facebook/fresco/blob/master/fbcore/proguard-fresco.pro - it shouldn't matter though.

**Comment by oprisnik** [comment]
Ideally, you would not shop these classes for release builds (i.e. Flipper shouldn't be included), but if you must then you can change the Proguard rule to keep them, see 90ca8cdaee0207402becd9c2c68ab97bebae83a9
