### ISSUE TITLE
migrate off jcenter

### ISSUE THREAD

**Issue by jeremyrempel** [facebook/fresco#2585]
jcenter will be sunset on May 1, 2020 [announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by wizh** [comment]
Hi! Thank you for opening the issue, we're aware of this.

**Comment by npace** [comment]
Hello! 
Is there a timeline for the migration or any clarity regarding where you'll host the artifacts, e.g. maven central?

**Comment by mikehardy** [comment]
Interestingly (?), some of the artifacts are on mavenCentral (e.g., 2.0.0 and 2.3.0) and some are on jcenter (2.2.0 and 2.4.0)

Unfortunately the one react-native needs (which I am interested in) is 2.2.0, since 2.3.0 is not released yet (note: commit only on master, no release branch tag https://github.com/facebook/react-native/commit/280f524b491e7a36bb9f9a26e354bb8e125375ed)

And I suppose if react-native gets it together for 2.4.0 then we'll have the same problem :-)

**Comment by oprisnik** [comment]
Hey! @passy helped us fix our Maven Central release pipeline and we've released Fresco 2.5.0. So you should be able to migrate now.
