### ISSUE TITLE
how to use  dataSource.subscribe?

### ISSUE THREAD

**Issue by mio4kon** [facebook/fresco#265]
``` 
dataSource.subscribe (new BaseBitmapDataSubscriber () {


            @Override
            protected void onNewResultImpl(@Nullable Bitmap bitmap) {
                LogUtils._d (bitmap.toString ());
            }

            @Override
            protected void onFailureImpl(DataSource dataSource) {

            }
        }, executor);
```
API never talked about executor..

**Comment by mio4kon** [comment]
BTW,how can i use fresco to   `RelativeLayout.setBackground(drawable)` which the drawable is come from net.

**Comment by IanChilds** [comment]
There seem to be two separate issues here. For the first, I have updated the example in the docs to include the executor, which I guess is what you mean. 

For the second, I suggest you do not use RelativeLayout.setBackground(drawable), but instead have a SimpleDraweeView that is the same size as the RelativeLayout. That will ensure that your memory is released when it should be, rather than you having to worry about that yourself.

**Comment by mio4kon** [comment]
I got it , Thanks
