### ISSUE TITLE
Separate the native c++ code from imagepipeline mode

### ISSUE THREAD

**Issue by goodev** [facebook/fresco#316]
Can we separate the c++ code to another mode, and using the .so libs in imagepipeline mode, so the normal Java guys can just put the compiled .so libs to jinLibs folder in imagepipeline.  It's much easier for Java guys to build this project if they do not modify the c++ code.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by massimocarli** [comment]
Hi and sorry for the late answer. Your idea is basically to provide prebuilt .so files developers can add to the jniLibs if needed. This could be an approach but we prefer to built our code from the source. If the problem is the number of .so you can change the Android.mk files in order to merge the libraries into a single one. Anyway we're working to make all Fresco modules optionals so very soon you can decide which library include or exclude.
