### ISSUE TITLE
Question about MemoryTrimmableRegistry

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#338]
Is there any demo code for using MemoryTrimmableRegistry? 
Is it necessory to add ImagePipelineConfig.Builder.setMemoryTrimmableRegistry(new MemoryTrimmableRegistry() {...})?

**Comment by plamenko** [comment]
In short, yes, you'll have to provide your own implementation of MemoryTrimmableRegistry.
MemoryTrimmableRegistry should maintain a list of registered trimmables and should also listen for the system events in order to detect the low-memory conditions. When low-memory conditions occur, registry should notify its trimmables in order to release some memory.
We shall amend the documentation on how to do that.

**Comment by IanChilds** [comment]
See http://frescolib.org/docs/configure-image-pipeline.html#using-a-memorytrimmableregistry
