### ISSUE TITLE
The rounded border don't display outside the image.

### ISSUE THREAD

**Issue by MarkMjw** [facebook/fresco#348]
my code:
![5](https://cloud.githubusercontent.com/assets/4126838/7988094/38a83dc2-0b14-11e5-803b-b74c73fab43e.png)

the result:
![6](https://cloud.githubusercontent.com/assets/4126838/7988098/40618762-0b14-11e5-8ed0-d87beb5e95df.png)

but i want:
![4](https://cloud.githubusercontent.com/assets/4126838/7988102/48f15218-0b14-11e5-9720-e20515e8f138.png)

**Comment by plamenko** [comment]
This is by design. First the image gets rounded, and then the border gets drawn on top of it. The border is centered on the edge of the rounded image, meaning that half of its width gets drawn outside of the image, half of it inside the image. Furthermore, your border color has alpha set to 0x40 which makes it semi-transparent. That's why you see the image underneath the inner part of the border.
It also seems that you are using a wrong scale type as the bottom image looks smaller, so check that out too.

**Comment by MarkMjw** [comment]
OK，thanks.
