### ISSUE TITLE
Incorrect Uri scheme for local app assets

### ISSUE THREAD

**Issue by davidschreiber** [facebook/fresco#37]
Android assets may be accessed using an Uri of this format `file:///android_asset/...` but Fresco uses the `asset://...` scheme which leads to incompatibility with other solutions.

E.g. when switching using Square's Picasso with Fresco, all Uris need to be changed to work with Fresco.

**Comment by plamenko** [comment]
`file:///android_asset` is only for use with `WebView`. For example, `Universal Image Loader` uses `assets://image.png`. So, I'm afraid there is no standard convention here. The fact that `FileInputStream` cannot open `/android_asset/...` is enough to disqualify the `file` scheme from being used for this purpose.

**Comment by anotherdev** [comment]
Fresco should support `file:///android_asset/` instead of creating new scheme and don't documented clearly that `asset://` scheme is vendor specific.

Picasso: https://github.com/square/picasso/issues/332
Glide: http://stackoverflow.com/questions/29982341/using-glide-for-android-how-do-i-load-images-from-asset-and-resources
