### ISSUE TITLE
fresco docs have a problem? 'hierarchy.setPlaceholderImage(R.drawable.placeholderId);' can't find it

### ISSUE THREAD

**Issue by blackiedm** [facebook/fresco#40]
I can't find this method.
'hierarchy.setPlaceholderImage(R.drawable.placeholderId);

**Comment by tyronen** [comment]
It is in the [GenericDraweeHierarchy](http://frescolib.org/javadoc/reference/com/facebook/drawee/generic/GenericDraweeHierarchy.html#setPlaceholderImage\(int\)) class.

**Comment by plamenko** [comment]
mSimpleDraweeView.getHierarchy().setPlaceholderImage(...)

**Comment by blackiedm** [comment]
ok!I use `GenericDraweeHierarchyBuilder` and just find this method `setPlaceholderImage(Drawable)`.

**Comment by plamenko** [comment]
You can specify the placeholder image while building hierarchy:

    GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(resources)
        .setPlaceholderImage(...)
        .build()
    mDraweeView.setHierarchy(hierarchy);

But, you can also change the placeholder view of the existing hierarchy:

  hierarchy.setPlaceholderImage(...);
  OR
  mDraweeView.getHierarchy().setPlaceholderImage(...);

Note: I suggest that you always use `SimpleDraweeView`. However, if you are using `DraweeView`, rather than `SimpleDraweeView`, make sure that you parametrize your DraweeView.

   `DraweeView<GenericDraweeHierarchy>`

otherwise `getHierarchy()` won't return `GenericDraweeHierarchy`, but a more restricted interface `DraweeHierarchy`. In that case you would have to cast.

**Comment by blackiedm** [comment]
@plamenko ok! I get it!
