### ISSUE TITLE
Animate scaling in SimpleDraweeView

### ISSUE THREAD

**Issue by nishantjain91** [facebook/fresco#418]
Is there any way to animate scale type of simpleDraweeView from CROP_CENTER to CENTER_INSIDE?

**Comment by plamenko** [comment]
Unfortunately this is not supported out of the box. You could try by setting the matrix instead of the scaletype with `GenericDraweeHierarchyBuilder.setActualImageMatrix`. Then you could perhaps animate the matrix from one to the other. But we'd first have to expose `GenericDraweeHierarchy.setActualImageMatrix`, and even then this would be tricky to do.
If you decide to play with this, you can use ScalingUtils.getTransform to get the actual matrix for a particular scale type.

**Comment by nishantjain91** [comment]
Thanks. I'll try that

**Comment by LiuDeng** [comment]
@nishantjain91 have you find any sulotion？

**Comment by sagartrehan** [comment]
Method setActualImageMatrix is deprecated with comments "This is not something that you want". 

Is there any alternative for this method.
