### ISSUE TITLE
Any way to synchronously load images into cache?

### ISSUE THREAD

**Issue by lewis6991** [facebook/fresco#446]
Is there any way to load images synchronously (on the main thread) into cache rather than running the loads on the background thread. The use case for this is that I want to run an initial load of images before displaying a listview contents. This way, at startup, the images will appear instantly with the rest of the content rather than fading into view a split-second after. The images are stored locally in a content provider.

**Comment by plamenko** [comment]
This is a bad practice so we don't support this. You should probably rethink how you display the content because blocking the user until the images are loaded seems like a really bad user experience. What if the images have to be downloaded? Do you really want to wait for dozens of seconds until all of them are downloaded?
