### ISSUE TITLE
In more than 5.0 of the use of fresco will be very card or even oom why?

### ISSUE THREAD

**Issue by liumouren** [facebook/fresco#489]
In more than 5.0 of the use of fresco will be very card or even oom why?

**Comment by IanChilds** [comment]
There are a number of issues that address this question - on 5.0 and above, the images are stored on the java heap rather than in ashmem, which can lead to an increase in OOMs. You should make sure to resize your images correctly and release the images when you have finished with them so that you don't see this problem.
