### ISSUE TITLE
Why is fresco a singleton?

### ISSUE THREAD

**Issue by danhawkes** [facebook/fresco#521]
In the 'getting started' text, there's this instruction:

> Near your application startup, before your app calls setContentView(), initialize the Fresco class. You should only call Fresco.initialize once. Your Application class would be a good place. Doing it in each Activity is wrong.

If I have a library that uses fresco, and an app that uses the library, this requirement creates ambiguity about if/when fresco's been initialised, and with what configuration.

What about adopting a parameterised constructor/builder, like [picasso](http://square.github.io/picasso/)?

**Comment by plamenko** [comment]
It makes little sense to have multiple instances of Fresco (because each would have their own memory cache, etc. which would be suboptimal). That's why it is a singleton.
Application can be composed of several independent modules that need not to know about each other. Several of those modules may require imaging functionality and for the reasons explained above, they should not have their own instance of Fresco, but should use the one and only instance configured on the app level. Another reason why configuration should not happen in any of those submodules is because they are not aware of the bigger scheme under which they operate.

For example, your app may have a chat section where there is a profile picture next to each message, and no other pictures than that. Then you might have another news-feed like section where there are stories accompanied by the authors' profile pictures, but may also contain the actual pictures that may be big. If the Fresco initialization is being done in the chat section, one might conclude that the imaging library should be configured with a small memory cache, because there is no need to keep that many profile pictures in the memory cache and they are all reasonably small. If each section has their own instance of Fresco, then the same profile picture might be contained twice, each in a separate memory cache. The only way to properly solve this is to do the initialization/configuration on the application level.

That being said, the library you are referring to should really not initialize Fresco. Please let me know if that answers your question. If I actually misunderstood your question, it would help if you  provide some code examples of the API that you would prefer.
