### ISSUE TITLE
The demo project isn't building 

### ISSUE THREAD

**Issue by yrizk** [facebook/fresco#618]
a failure with the task `:imagepipeline:ndk_build_bitmaps`
stacktrace: https://gist.github.com/fcaebdec0bd61826a3b4.git
I tried installing the NDK thinking that might the issue. I'm all out of ideas.

**Comment by massimocarli** [comment]
We're getting a 404 with the stacktrace link you reported.

**Comment by yrizk** [comment]
Woops. 
here's the good link https://gist.github.com/yrizk/fcaebdec0bd61826a3b4

**Comment by massimocarli** [comment]
Please double check your NDK configuration. The ndk_build tool in not in the classpath as shown here.

Caused by: java.io.IOException: Cannot run program "ndk-build" (in directory "/Users/yohannarizk/code/stuff/lib/fresco/imagepipeline"): error=2, No such file or directory
at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
... 4 more
Caused by: java.io.IOException: error=2, No such file or directory
... 5 more

**Comment by yrizk** [comment]
hmm that is strange. I did add the ndk to my PATH. I'll look into this again. thank you for the quick response.

**Comment by srajesh529** [comment]
yes , i am also getting same issue.i am setting the ndk path also getting the same issue.below is my error log.
Error:Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> Process 'command 'ndk-build.cmd'' finished with non-zero exit value 2

How to solve this issue?

**Comment by yanshuai615270** [comment]
I met this kind of problem. First of all You have to give your NDK path in **local.properties** of your app.
e.g. ndk.dir=/home/user/bin/android_ndk/android-ndk-r10e
