### ISSUE TITLE
Gradle tries to get fbcore jar instead of aar

### ISSUE THREAD

**Issue by PavelSynek** [facebook/fresco#672]
I tried to update to the newest 0.8.0 version but I got following error:

> Could not find fbcore.jar (com.facebook.fresco:fbcore:0.8.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/facebook/fresco/fbcore/0.8.0/fbcore-0.8.0.jar

https://jcenter.bintray.com/com/facebook/fresco/fbcore/0.7.0/
https://jcenter.bintray.com/com/facebook/fresco/fbcore/0.8.0/

**Comment by kaedea** [comment]
Error:A problem occurred configuring project ':app'.
> Could not find fbcore.jar (com.facebook.fresco:fbcore:0.8.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/facebook/fresco/fbcore/0.8.0/fbcore-0.8.0.jar

**Comment by ffelini** [comment]
I get the same error

**Comment by UmeshAawte** [comment]
I got it too,

A problem occurred configuring project ':app'.
> Artifact 'fbcore.jar (com.facebook.fresco:fbcore:0.8.0)' not found.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/facebook/fresco/fbcore/0.8.0/fbcore-0.8.0.jar

**Comment by ffelini** [comment]
Any updates here?

**Comment by tyronen** [comment]
The problem seems to be that you're trying to download fbcore-0.8.0.jar. You should be downloading fbcore-0.8.0.aar. How are the `repositories` and `dependencies` sections in your `build.gradle` set up?

**Comment by bluef** [comment]
I met the same problem, simply
```
compile 'com.facebook.fresco:fresco:0.8.0'
```
changing the version from 0.8.0 back to 0.7.0 makes everything work again

**Comment by ffelini** [comment]
We all know :)

I just wanted to give a try to the newest 0.8.0 version as it contains many fixes.

**Comment by PavelSynek** [comment]
@tyronen my top-level build.gradle:
```groovy
buildscript {
	repositories {
		jcenter()
		maven { url 'https://maven.fabric.io/public' }
	}
	dependencies {
		classpath 'com.android.tools.build:gradle:1.3.1'

		..........
	}
}

allprojects {
	repositories {
		jcenter()
		maven { url 'https://maven.fabric.io/public' }
		maven { url "https://jitpack.io" }
	}
}
```

And in my module's build.gradle I have 
```groovy
dependencies {
...
compile 'com.facebook.fresco:fresco:0.8.0'
compile 'com.facebook.fresco:imagepipeline-okhttp:0.8.0'
...
}
```

I tried gradlew generateDebugSources --info/debug/stacktrace, but found no relevant info there (I can post full logs if needed)

**Comment by JadenGu** [comment]
Upgrade your Gradle can solve this problem. I just tried and it worked.

**Comment by PavelSynek** [comment]
Clearing Gradle cache with gradle build --refresh-dependencies solved the problem.

**Comment by ffelini** [comment]
No luck on my side.
Tried Build->Clean Project
Tried to remove build folder
Tried many times Gradle Sync

Nothing helps

**Comment by PavelSynek** [comment]
In Android Studio, execute Gradle task build --refresh-dependencies from right Gradle menu.

**Comment by ffelini** [comment]
Unfortunatelly same situation after executing gradle --refresh-dependencies 

 Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find fbcore.jar (com.facebook.fresco:fbcore:0.8.0).
13:55:45.582 [ERROR] [org.gradle.BuildExceptionReporter] Searched in the following locations:
13:55:45.582 [ERROR] [org.gradle.BuildExceptionReporter]     https://jcenter.bintray.com/com/facebook/fresco/fbcore/0.8.0/fbcore-0.8.0.jar
13:55:45.582 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:38)
13:55:45.582 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifactFromCache(CachingModuleComponentRepository.java:260)
13:55:45.583 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$LocateInCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:244)
13:55:45.583 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.BaseModuleComponentRepositoryAccess.resolveArtifact(BaseModuleComponentRepositoryAccess.java:54)
13:55:45.583 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedModuleComponentRepository$CachedAccess.resolveArtifact(InMemoryCachedModuleComponentRepository.java:82)
13:55:45.583 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:116)
13:55:45.583 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifact(RepositoryChainArtifactResolver.java:63)
13:55:45.584 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectArtifactResolver.resolveArtifact(ProjectArtifactResolver.java:65)
13:55:45.584 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ContextualArtifactResolver$3.execute(ContextualArtifactResolver.java:61)
13:55:45.584 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ContextualArtifactResolver$3.execute(ContextualArtifactResolver.java:59)
13:55:45.584 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Transformers$4.transform(Transformers.java:137)
13:55:45.585 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
13:55:45.585 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
13:55:45.585 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ContextualArtifactResolver$4.run(ContextualArtifactResolver.java:69)
13:55:45.585 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
13:55:45.585 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
13:55:45.585 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
13:55:45.586 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
13:55:45.586 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
13:55:45.586 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
13:55:45.586 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ContextualArtifactResolver.executeInContext(ContextualArtifactResolver.java:67)
13:55:45.586 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ContextualArtifactResolver.resolveArtifact(ContextualArtifactResolver.java:59)
13:55:45.586 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingArtifactResolver.resolveArtifact(ErrorHandlingArtifactResolver.java:53)
13:55:45.587 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.DefaultResolvedConfigurationBuilder$LazyArtifactSource.create(DefaultResolvedConfigurationBuilder.java:129)
13:55:45.587 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.DefaultResolvedConfigurationBuilder$LazyArtifactSource.create(DefaultResolvedConfigurationBuilder.java:116)
13:55:45.587 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.artifacts.DefaultResolvedArtifact.getFile(DefaultResolvedArtifact.java:93)
13:55:45.587 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.DependencyManager.addDependency(DependencyManager.java:831)
13:55:45.588 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.DependencyManager.addDependency(DependencyManager.java:744)
13:55:45.588 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.DependencyManager.addDependency(DependencyManager.java:744)
13:55:45.588 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.java:268)
13:55:45.588 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.java:133)
13:55:45.588 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.groovy:272)
13:55:45.588 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager$8.call(VariantManager.java:591)
13:55:45.589 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager$8.call(VariantManager.java:588)
13:55:45.589 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
13:55:45.589 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.Recorder$record.call(Unknown Source)
13:55:45.589 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:69)
13:55:45.589 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:587)
13:55:45.590 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:690)
13:55:45.590 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:452)
13:55:45.590 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:271)
13:55:45.590 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy:448)
13:55:45.590 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy)
13:55:45.590 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
13:55:45.591 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
13:55:45.591 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
13:55:45.591 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:447)
13:55:45.591 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy:388)
13:55:45.591 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy)
13:55:45.591 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
13:55:45.592 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
13:55:45.592 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
13:55:45.592 [ERROR] [org.gradle.BuildExceptionReporter]        at com.android.build.gradle.BasePlugin$_createTasks_closure13.doCall(BasePlugin.groovy:387)
13:55:45.593 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
13:55:45.593 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
13:55:45.594 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
13:55:45.595 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
13:55:45.595 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
13:55:45.595 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.proxy.$Proxy10.afterEvaluate(Unknown Source)
13:55:45.596 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
13:55:45.596 [ERROR] [org.gradle.BuildExceptionReporter]        ... 115 more
13:55:45.597 [ERROR] [org.gradle.BuildExceptionReporter] 
13:55:45.597 [LIFECYCLE] [org.gradle.BuildResultLogger] 
13:55:45.597 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED

**Comment by PavelSynek** [comment]
No idea how to fix that, reopening....

**Comment by ffelini** [comment]
Anyone with the same problem? Any workarounds? Tricks?

**Comment by JadenGu** [comment]
Upgrade gradle in gradle-wrapper.properties works for me.

**Comment by PavelSynek** [comment]
@JadenGu I had the problem with latest Gradle 2.8.
@ffelini try manually deleting $HOME/.gradle/caches folder, it should force Gradle to redownload all dependencies

**Comment by JadenGu** [comment]
@PavelSynek 
I'm using 2.7. It's OK.
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.7-all.zip

**Comment by ffelini** [comment]
Unfortunatelly nothing helps.
Tried to update gradle to version 2.7. Same issue.

**Comment by leofirespotter** [comment]
So anything here?

**Comment by tyronen** [comment]
It could also be you have a local Maven repo which has an incorrect pom file.

If you have a $HOME/.m2/repository/com/facebook/fresco directory, delete it.

**Comment by ffelini** [comment]
Ok guys . So here is my solution :)

I just removed the project completly and imported it again (checking out from github).

**Comment by tyronen** [comment]
If you are still experiencing problems, try again with v0.8.1.
