### ISSUE TITLE
How can I do conditional processing in BasePostprocessor?

### ISSUE THREAD

**Issue by skptl** [facebook/fresco#686]
@Override
public void process(Bitmap destBitmap, final Bitmap sourceBitmap) {
        if(process)
            process(mContext, destBitmap, sourceBitmap);
        else
            destBitmap = sourceBitmap;
}

**Comment by michalgr** [comment]
Override this method: https://github.com/facebook/fresco/blob/94ce1dee0733300fe2c029382e0c454169db81b8/imagepipeline/src/main/java/com/facebook/imagepipeline/request/BasePostprocessor.java#L47

**Comment by michalgr** [comment]
Avoiding the copy will require some changes to the Fresco code. The easiest way todo that would be to change this method: https://github.com/facebook/fresco/blob/v0.8.0/imagepipeline/src/main/java/com/facebook/imagepipeline/request/BasePostprocessor.java#L47 to accept CloseableReference<Bitmap> instead of Bitmap and override it in your subclass. When you don't want to modify the bitmap you can simply return input reference (cloned).

**Comment by michalgr** [comment]
If you don't mind creating new bitmap then you can simply copy pixels like here: https://github.com/facebook/fresco/blob/v0.8.0/imagepipeline/src/main/java/com/facebook/imagepipeline/request/BasePostprocessor.java#L79

**Comment by skptl** [comment]
Thanks @michalgr. For the first option, I will have to build fresco and use. So for now I would add a Postprocessor on a condition instead of checking condition inside Postprocessor. I use this in a intense view and cannot create a new bitmap every time.

**Comment by kirwan** [comment]
I'm cleaning up very old issues. If this still causes problems please comment and we can re-open.
