### ISSUE TITLE
What's new in 0.8.0?

### ISSUE THREAD

**Issue by tianlang** [facebook/fresco#701]
如题

**Comment by HomHomLin** [comment]
我也想知道。他们都不写更新日志。

**Comment by tianlang** [comment]
看见更新了0.8.0，我立刻就把gradle里面的0.7.0+改成了0.7.0...

**Comment by kaedea** [comment]
>Allow Bitmap.Config to be set by caller
New BaseBooleanSubscriber class
New experimental code to put encoded images in ashmem (JellyBean and below)
New experimental code to decode WebP directly on older platforms instead of transcoding
New sample apps to demonstrate shared transitions and write-you-own uri
Added AQuery to comparison app
Lotsa bug fixes

你们都不看这些的嘛

**Comment by tianlang** [comment]
咦，这个在哪里看的

**Comment by tianlang** [comment]
哦 我看到了  在这里 https://github.com/facebook/fresco/releases
