### ISSUE TITLE
Hope add Animatable pause rather than stop and start

### ISSUE THREAD

**Issue by LiuDeng** [facebook/fresco#707]
Hope add Animatable pause rather than stop and start

**Comment by massimocarli** [comment]
Android `Animatable` interface doesn't have the `pause()` operation so probably you could implement this as a specific `Animatable ` implementation feature. At the moment we don't plan to do that.
Thanks

**Comment by oprisnik** [comment]
This is now possible (f914b7a8e2acd2313ee785b48aee7722f3d7da9a) thanks to @gtpark. It will be available in the next release (or right now if you're using the GitHub source directly).
However, since `Animatable` is an Android interface, you have to pause the animation differently, see f914b7a8e2acd2313ee785b48aee7722f3d7da9a
