### ISSUE TITLE
SimpleDraweeView cant load an image on listView

### ISSUE THREAD

**Issue by ChoiKyubum** [facebook/fresco#801]
other images are loaded all right.

but, one of images is not loaded well

it just hold the place holder image in drawable

image url is 

https://s3-ap-northeast-1.amazonaws.com/drogen-bucket/item/LOBIT 300GT/1448867012241_lobit-300.jpg

it appear in my website and the other site

plz check this porb,, i cant fix this

**Comment by balazsbalazs** [comment]
Can you provide more details please?
Are you saying that if I download the image in the above URL and put it as a placeholder image it will not appear?
If yes, can you try it in a very simple sample application, which only has one SimpleDraweeView and this image as a placeholder. Is it working there?

**Comment by massimocarli** [comment]
Hi, the problem is the space into the URL you provided. It should be responsibility of the caller to encode it using classes like http://docs.oracle.com/javase/7/docs/api/java/net/URLEncoder.html. In your case the URL should be:

https://s3-ap-northeast-1.amazonaws.com/drogen-bucket/item/LOBIT%20300GT/1448867012241_lobit-300.jpg

with the %20 in place of the space.

**Comment by PiyushPoriya** [comment]
Hi, I am trying to display image from gallery but some images not displaying. I have double check every time i am getting path.
