### ISSUE TITLE
Use XML-defined styles in a hierarchy

### ISSUE THREAD

**Issue by Gerald09** [facebook/fresco#807]
I define a style like this:

``` xml
<style name="AvatarSimpleDraweeViewProperties">
        <item name="packageName:actualImageScaleType">centerCrop</item>
        <item name="packageName:placeholderImage">@drawable/user_avatar_default</item>
        <item name="packageName:placeholderImageScaleType">centerCrop</item>
        <item name="packageName:failureImage">@drawable/user_avatar_default</item>
        <item name="packageName:failureImageScaleType">centerCrop</item>
        <item name="packageName:viewAspectRatio">1</item>
        <item name="packageName:roundAsCircle">true</item>
    </style>
```

Can I create a GenericDraweeHierarchy instance with the values inflated from this xml?

**Comment by plamenko** [comment]
Hi, you can't inflate only the hierarchy at the moment, but you can inflate `GenericDraweeView`. If you just need the hierarchy, you could make a pull request that extracts `GenericDraweeHierarchy` [inflation logic] (https://github.com/facebook/fresco/blob/94ce1dee0733300fe2c029382e0c454169db81b8/drawee/src/main/java/com/facebook/drawee/view/GenericDraweeView.java#L91) out of `GenericDraweeView` (preferably to a separate file, `GenericDraweeHierarchyInflator` or similar). I wanted to do that since long time ago, but there was always something else.

**Comment by oprisnik** [comment]
You can use `GenericDraweeHierarchyInflater.inflateHierarchy(Context context, AttributeSet attrs)` or GenericDraweeHierarchyInflater.inflateBuilder(Context context, AttributeSet attrs)` to get a hierarchy or a builder.
