### ISSUE TITLE
add ripple effect layer with palette.

### ISSUE THREAD

**Issue by desmond1121** [facebook/fresco#811]
Hi, I'm a Chinese developer and I've pay attention to Fresco longtime and I always want to contribute something to it. 
Several days ago, I've made a repo [RippleCompat](https://github.com/desmond1121/RippleCompat), use a drawable to make view be "ripple" just like in Material Design. Palette ripple color built in, too. Can I add it to Fresco and make it become one of a Drawable Layer?

**Comment by plamenko** [comment]
Hi, your project looks nice! I think in this case it is better if we keep `RippleCompat` as a separate project, instead of being a part of Fresco library. That way we avoid coupling two libraries that should remain separate.
RippleCompat being a separate library doesn't make it incompatible with Fresco in any way. That said, I definitely would like to help you make your project compatible with Fresco. I briefly looked at the source code and I have some suggestions.
I noticed that at the moment RippleCompat heavily depends on the view being ImageView. This imposes some complexities, none of which are required with Fresco.
Display layer of fresco is called Drawee. Drawee supports overlay drawables and ripple effect feels like a perfect use case for that. Drawee already propagates state changes correctly, so, to make a ripple effect with Drawee, all you really need to do is implement a single Drawable that is state aware. Like Android's `StateListDrawable`. When the state changes to `state_pressed` your drawable can start performing the ripple-effect animation. When the state changes to something other than `state_pressed` you stop the animation.
You do not need to temper with the actual image in the ImageView, or with the scale types, etc. This is both dangerous and unnecessary.
The only thing that Drawee doesn't support at the moment is passing the touch event to the drawable and therefore we don't have coordinates of the touch. We can add support for that, and this is really the only change that should be done in Fresco.

After you implement your drawable that is state aware, this is how it can be set to Fresco / Drawee:

Programmatically:

    GenericDraweeHierarchyBuilder.setOverlay(rippleEffectDrawable)

XML:

    fb:overlayImage="@drawable/rippleEffectDrawable"

This is a simple example of Android's StateListDrawable that is state-aware and just displays the `underlyingDrawable` when you tap on the view:

    StateListDrawable stateListDrawable = new StateListDrawable();
    stateListDrawable.addState(new int[]{android.R.attr.state_pressed}, underlyingDrawable);

I strongly suggest that you provide a similar API. Just a single drawable that can be inflated from XML or instantiated programmatically with the given parameters. Then we just set that drawable as an overlay.

**Comment by desmond1121** [comment]
@plamenko Thank you for your advice!
I've noticed that fresco have built-in matrix and scale type layer, and my code do so many trival work. I would like to reduce mine code to make it only have single responsibility - ripple effect, and make it become more compatible:)

**Comment by plamenko** [comment]
Yes exactly. Ideally you should not be solving scaling and other stuff unless absolutely necessary. This also makes your library incompatible with anything that does scaling and other stuff in a different way than your library. It is best if the code can be kept modularized so that your library only really does the ripple effect.
I understand why you need this logic with the ImageView, but luckily, with Fresco, we can make it much simpler.
If I were you I would refactor your library like so:
* Create a `RippleEffectDrawable` that just draws the ripple effect onto canvas (based on the pressed-state, and a public method `setRippleCenter(float x, float y)`.
* For your effect to work with Fresco, the above drawable is enough.
* To support the plain ImageView for those who do not use Fresco, I would offer two ways:

1. By extending `ImageView`. The advantage is that you do not need to deal with scale type, and you do not temper with the view background. The drawback is that Java does not support multiple inheritance which means that this is not always a suitable approach.

```
    onDraw(canvas) {
      super.draw(canvas);
      mRippleEffectDrawable.draw(canvas);
    }
    
    onTouchEvent(event) {
      mRippleEffectDrawable.setRippleCenter(event.x, event.y);
      or
      mRippleEffectDrawable.onTouchEvent(event)
    }
```

2. By modifying the ImageView in the way that you do now. This has exactly the opposite trade-off. You have to deal with the scaling, background, etc, but this might also work with some other Custom views that extend ImageView. Even though, you should be aware that this is a dangerous practice.

**Comment by desmond1121** [comment]
@plamenko Thank you for your advice:)

**Comment by plamenko** [comment]
FYI, Android introduced the `setHotspot(float x, float y)` method that serves for this purpose.
