### ISSUE TITLE
I want to load a video thumbnail,how can i do that with fresco .thanks

### ISSUE THREAD

**Issue by kingty** [facebook/fresco#856]

**Comment by ongakuer** [comment]
```mSimpleDraweeView.setImageURI(Uri.fromFile(new File(videoPath)));```

**Comment by Abthul** [comment]
Sometimes , for some files, the videothumbnail fails. any idea how the video thumbnails are loaded in fresco?

**Comment by lambdapioneer** [comment]
Hi @Abthul, we are relying on Android's `ThumbnailUtils` in our `LocalVideoThumbnailProducer`:

https://github.com/facebook/fresco/blob/84aeab6895f3177cee473e85656cf898112f263f/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/LocalVideoThumbnailProducer.java#L62

**Comment by Abthul** [comment]
@lambdapioneer  Yeah, i checked it, but it doesn't load any video thumbnails. I have modified the fresco samples comparison app to load video uris instead of image uris, it doesn't show any thumbnails, just modified the projection and selection and the uri. It shows Blank Thumbnails and the Loading... text doesn't change. What could be the problem. 

Same kind of implementation present in Glide as well, there they go one step further and directly use the **MediaMetadataRetriever** instead of Thumbnail utils. It works fine with the Glide. I would want to try the Fresco for my project as it has real Loading, instead of Cache Loading in Glide.

Could you throw some points on this video thumbnail loading failure.
