### ISSUE TITLE
Setting .setDownsampleEnabled(true) prevents pictures to auto-rotate

### ISSUE THREAD

**Issue by aleien** [facebook/fresco#876]
I had trouble with auto-rotating pictures with orientation in their exif, but figured out that downsampling was causing troubles.

**Comment by tyronen** [comment]
Can you elaborate? What was the problem? And what version of Fresco are you using?

**Comment by aleien** [comment]
I am using 0.8.1. 
I had problem with loading images from phone gallery on some devices - some images would show up rotated by 90 degrees. I figured out that images that have 90 or 270 (i.e portrait orientation) in their exif would show up horizontally. I read that fresco can auto-rotate images, so I tried setting .setAutoRotateEnabled(true), but it didn't have any effect. So I just started to experiment with fresco settings and figured out that setting .setDownsampleEnabled(false) solved that problem.

**Comment by kirwan** [comment]
You're right about this bug. This has come up in #962 too.

We've discussed a solution internally but I can't say right now when we'll fix this.

**Comment by AllenVork** [comment]
How to add setDownSampleSize option dynamically? I wanna load a lot of images, so i use this option to make my image small.But when i touch the image, i must show the original image.The problem is the original image is muzzy.

**Comment by kirwan** [comment]
I've just completed a series of changes to be included in the next Fresco release, 0.14.0.

This adds a `RotationOptions` class which can be specified when building an image request. As well as having a new API, several fixes have been made with respect to rotation when downscaling is enabled, when a postprocessor is attached and other cases we were aware of.

The default behaviour will now be to fix the rotation in the pipeline so that by the time a post-processor is triggered, the image is fixed.

The initial commit for these changes is 36dd783.
