### ISSUE TITLE
The fresco 0.7.0 displays progressive JPEG in low quality

### ISSUE THREAD

**Issue by CharlesLin99** [facebook/fresco#904]
Hi,  I am using fresco 0.7.0 to preview photos and some photos display in low quality and some are right. The photos displays wrong are progressive JPEGs. 
One display snapshot as below,
![low_resolution_in_ceter](https://cloud.githubusercontent.com/assets/14235815/12254555/f52efa94-b924-11e5-8a5a-dcca8a6037db.png)
The original photo as below,
![359b033b5bb5c9ea0b010379d139b6003bf3b3bd](https://cloud.githubusercontent.com/assets/14235815/12254563/044d69a2-b925-11e5-972d-e5ffade5c1d8.jpg)

The xml code here,
<com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/full_preview_item_image_view"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    fresco:actualImageScaleType="center"/>
The source code here,
 simpleDraweeView.setImageURI(Uri.parse("file:///storage/emulated/0/Download/359b033b5bb5c9ea0b010379d139b6003bf3b3bd.jpg"));

**Comment by michalgr** [comment]
Try version 0.8.1, I think this is fixed by https://github.com/facebook/fresco/commit/b1f83c9d9d441da96b637a3c55e04348a12ee49e. When you load jpeg from disk Fresco will first check if the jpeg contains exif thumbnail. If the thumbnail is big enough it will be used instead. The diff I pointed to fixes the number that thumbnail's size is compared with if no expected dimensions are provided (was -1 previously :))
