### ISSUE TITLE
No possibility to set new maximum retry amounts

### ISSUE THREAD

**Issue by emce** [facebook/fresco#941]
I went through the code and didn't find any way to do this - is there a way?

**Comment by plamenko** [comment]
If you are referring to tap-to-retry functionality, this is not supported at the moment.
In order to support that, we need to add the `setMaxTapToRetryAttempts` setter to [RetryManager] (https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/drawee/src/main/java/com/facebook/drawee/components/RetryManager.java) and the corresponding option to the [AbstractDraweecontrollerBuilder] (https://github.com/facebook/fresco/blob/0f3d52318631f2125e080d2a19f6fa13a31efb31/drawee/src/main/java/com/facebook/drawee/controller/AbstractDraweeControllerBuilder.java).
Feel free to send a pull request :)

**Comment by erikandre** [comment]
Closing since this issue is not prioritized to be implemented in the foreseeable future.
If this is a feature that you need, please consider contributing a pull request to Fresco!
