### ISSUE TITLE
Sometimes there is something wrong with image in disk cache

### ISSUE THREAD

**Issue by starkingwx** [facebook/fresco#942]
I occasionally saw an image is bad when displaying, then I searched it in disk cache and found it like this:
![wwqhw8dfpe22ltxsiu_pwlqss8s cnt](https://cloud.githubusercontent.com/assets/1582967/12506608/54bf32a4-c12b-11e5-949c-812f357b2f23.jpg)

**Comment by plamenko** [comment]
This looks like a baseline JPEG image that is not fully downloaded. That's weird because if the network request doesn't finish with all data being received, it should fail. This leaves a couple of options:
1. Server is misbehaving
2. Networking library is misbehaving
3. There is a bug in Fresco

Can you provide more information on what version of Fresco are you using, do you use a custom networking stack, where this image comes from (uri)?

**Comment by starkingwx** [comment]
Oh thank u for reply, I find that it's the issue of server.
image url: http://114.215.204.97:29102/api/avatar/7e34b0a2-3ed5-45df-b7bb-dcc8de13a7bf!200

**Comment by starkingwx** [comment]
server has fixed it.
