### ISSUE TITLE
SimpleDraweeView sends onClick events incorrectly

### ISSUE THREAD

**Issue by edarn** [facebook/fresco#943]
Hi!

I´m having problem with the SimpleDraweeView to which I register an OnClickListener. The problem I am seeing is that the OnClick event is sent to often. It gets sent even if you swipe, pinch-to-zoom or any other gesture. It seems like the onClick is sent always if Touch.DOWN is followed by Touch.UP events. It needs to NOT send onClick when there is also Touch.MOVE events sent.

Please test with this simple code to show the error.

        debugView.setImageURI(Uri.parse("http://lorempixel.com/800/600/"));
        debugView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                System.out.println("OnClick");
            }
        });

**Comment by plamenko** [comment]
I doubt this is a Fresco bug. DraweeView just forwards the touch event to the parent class `View` which detects and calls `onClick`.
Just to isolate where the issue is, are you using Fresco's tap-to-retry functionality? If so that might be related. If not, then I suggest that you try to replace SimplaDraweeView with an ImageView (no need to set any image) and see if you get the same onClick behavior. If you do, that means this is due to Android's implementation, not Fresco.

**Comment by edarn** [comment]
True, sorry for bad debugging on my side. Closing the issue, due to error is not due to Fresco
