### ISSUE TITLE
Gallery using viewpager cannot scroll when zoom image with zoomabledrawee 

### ISSUE THREAD

**Issue by hanhmh1203** [facebook/fresco#951]
Hi Friends,
I have Issue, when I using library fresco with control zoomabledrawee, while I zoom it, and scroll image to end of left or end of right, and contineu scroll, viewpager cannot scroll to next image.
plz help me!!!.

**Comment by hanhmh1203** [comment]
plz help me !!

**Comment by plamenko** [comment]
ZoomableDraweeView is really just an example implementation. It is not intended to be used as is.

The problem you have happens because the sample implementation of ZoomableDraweeView just forwards all of the touch events to the DefaultZoomableController which always handles them. In order to workaround this, you have to implement some additional logic in ZoomableDraweeView.onTouchEvent and/or ZoomableController.

Anyhow, for this kind of questions please ask on [StackOverflow](http://stackoverflow.com/questions/ask?tags=fresco,android) with the tag fresco and android. We're answering questions on stackoverflow but there are a lot more people in the community who can help you.

**Comment by hanhmh1203** [comment]
Thanks :)
