### ISSUE TITLE
SHA-1 in SecureHashUtil.java

### ISSUE THREAD

**Issue by jairoserranosp** [facebook/fresco#965]
Deprecation of SHA-1 is running. So, why there is no option to use SHA-2 family hashes in the  SecureHashUtil.java file?

**Comment by plamenko** [comment]
Because it's not required for Fresco. We use SHA1 to generate a unique filename when disk-caching a particular image. The worst thing that can happen should a collision occur is Fresco displaying another image that happened both to already be in your disk cache and simultaneously have the same SHA1 hash. Chances of this happening are astronomically low, and even if it happens the impact would be negligible.

**Comment by jairoserranosp** [comment]
Thx for your answer!
